// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: agent/node.proto

package agent

import (
	common "github.com/zhinea/sylix/internal/infra/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployNodeComposeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType        string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	ComposeContent  string                 `protobuf:"bytes,3,opt,name=compose_content,json=composeContent,proto3" json:"compose_content,omitempty"`
	PriorityStartup int32                  `protobuf:"varint,4,opt,name=priority_startup,json=priorityStartup,proto3" json:"priority_startup,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeployNodeComposeRequest) Reset() {
	*x = DeployNodeComposeRequest{}
	mi := &file_agent_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployNodeComposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployNodeComposeRequest) ProtoMessage() {}

func (x *DeployNodeComposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployNodeComposeRequest.ProtoReflect.Descriptor instead.
func (*DeployNodeComposeRequest) Descriptor() ([]byte, []int) {
	return file_agent_node_proto_rawDescGZIP(), []int{0}
}

func (x *DeployNodeComposeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DeployNodeComposeRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *DeployNodeComposeRequest) GetComposeContent() string {
	if x != nil {
		return x.ComposeContent
	}
	return ""
}

func (x *DeployNodeComposeRequest) GetPriorityStartup() int32 {
	if x != nil {
		return x.PriorityStartup
	}
	return 0
}

type DeployNodeComposeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           string                 `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "running", "success", "failed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployNodeComposeResponse) Reset() {
	*x = DeployNodeComposeResponse{}
	mi := &file_agent_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployNodeComposeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployNodeComposeResponse) ProtoMessage() {}

func (x *DeployNodeComposeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployNodeComposeResponse.ProtoReflect.Descriptor instead.
func (*DeployNodeComposeResponse) Descriptor() ([]byte, []int) {
	return file_agent_node_proto_rawDescGZIP(), []int{1}
}

func (x *DeployNodeComposeResponse) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *DeployNodeComposeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StopNodeComposeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopNodeComposeRequest) Reset() {
	*x = StopNodeComposeRequest{}
	mi := &file_agent_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopNodeComposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopNodeComposeRequest) ProtoMessage() {}

func (x *StopNodeComposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopNodeComposeRequest.ProtoReflect.Descriptor instead.
func (*StopNodeComposeRequest) Descriptor() ([]byte, []int) {
	return file_agent_node_proto_rawDescGZIP(), []int{2}
}

func (x *StopNodeComposeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetNodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeStatusRequest) Reset() {
	*x = GetNodeStatusRequest{}
	mi := &file_agent_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeStatusRequest) ProtoMessage() {}

func (x *GetNodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetNodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_node_proto_rawDescGZIP(), []int{3}
}

func (x *GetNodeStatusRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetNodeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "running", "stopped", "failed", "unknown"
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeStatusResponse) Reset() {
	*x = GetNodeStatusResponse{}
	mi := &file_agent_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeStatusResponse) ProtoMessage() {}

func (x *GetNodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeStatusResponse.ProtoReflect.Descriptor instead.
func (*GetNodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_node_proto_rawDescGZIP(), []int{4}
}

func (x *GetNodeStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetNodeStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetNodeLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Tail          int32                  `protobuf:"varint,2,opt,name=tail,proto3" json:"tail,omitempty"` // Number of lines to tail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeLogsRequest) Reset() {
	*x = GetNodeLogsRequest{}
	mi := &file_agent_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeLogsRequest) ProtoMessage() {}

func (x *GetNodeLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeLogsRequest.ProtoReflect.Descriptor instead.
func (*GetNodeLogsRequest) Descriptor() ([]byte, []int) {
	return file_agent_node_proto_rawDescGZIP(), []int{5}
}

func (x *GetNodeLogsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetNodeLogsRequest) GetTail() int32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

type NodeLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           string                 `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeLogResponse) Reset() {
	*x = NodeLogResponse{}
	mi := &file_agent_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeLogResponse) ProtoMessage() {}

func (x *NodeLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeLogResponse.ProtoReflect.Descriptor instead.
func (*NodeLogResponse) Descriptor() ([]byte, []int) {
	return file_agent_node_proto_rawDescGZIP(), []int{6}
}

func (x *NodeLogResponse) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

var File_agent_node_proto protoreflect.FileDescriptor

const file_agent_node_proto_rawDesc = "" +
	"\n" +
	"\x10agent/node.proto\x12\x05agent\x1a\x13common/common.proto\"\xa4\x01\n" +
	"\x18DeployNodeComposeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12'\n" +
	"\x0fcompose_content\x18\x03 \x01(\tR\x0ecomposeContent\x12)\n" +
	"\x10priority_startup\x18\x04 \x01(\x05R\x0fpriorityStartup\"E\n" +
	"\x19DeployNodeComposeResponse\x12\x10\n" +
	"\x03log\x18\x01 \x01(\tR\x03log\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"1\n" +
	"\x16StopNodeComposeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"/\n" +
	"\x14GetNodeStatusRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"E\n" +
	"\x15GetNodeStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"A\n" +
	"\x12GetNodeLogsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04tail\x18\x02 \x01(\x05R\x04tail\"#\n" +
	"\x0fNodeLogResponse\x12\x10\n" +
	"\x03log\x18\x01 \x01(\tR\x03log2\xc7\x02\n" +
	"\x10AgentNodeService\x12X\n" +
	"\x11DeployNodeCompose\x12\x1f.agent.DeployNodeComposeRequest\x1a .agent.DeployNodeComposeResponse0\x01\x12I\n" +
	"\x0fStopNodeCompose\x12\x1d.agent.StopNodeComposeRequest\x1a\x17.common.MessageResponse\x12J\n" +
	"\rGetNodeStatus\x12\x1b.agent.GetNodeStatusRequest\x1a\x1c.agent.GetNodeStatusResponse\x12B\n" +
	"\vGetNodeLogs\x12\x19.agent.GetNodeLogsRequest\x1a\x16.agent.NodeLogResponse0\x01B4Z2github.com/zhinea/sylix/internal/infra/proto/agentb\x06proto3"

var (
	file_agent_node_proto_rawDescOnce sync.Once
	file_agent_node_proto_rawDescData []byte
)

func file_agent_node_proto_rawDescGZIP() []byte {
	file_agent_node_proto_rawDescOnce.Do(func() {
		file_agent_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_node_proto_rawDesc), len(file_agent_node_proto_rawDesc)))
	})
	return file_agent_node_proto_rawDescData
}

var file_agent_node_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_agent_node_proto_goTypes = []any{
	(*DeployNodeComposeRequest)(nil),  // 0: agent.DeployNodeComposeRequest
	(*DeployNodeComposeResponse)(nil), // 1: agent.DeployNodeComposeResponse
	(*StopNodeComposeRequest)(nil),    // 2: agent.StopNodeComposeRequest
	(*GetNodeStatusRequest)(nil),      // 3: agent.GetNodeStatusRequest
	(*GetNodeStatusResponse)(nil),     // 4: agent.GetNodeStatusResponse
	(*GetNodeLogsRequest)(nil),        // 5: agent.GetNodeLogsRequest
	(*NodeLogResponse)(nil),           // 6: agent.NodeLogResponse
	(*common.MessageResponse)(nil),    // 7: common.MessageResponse
}
var file_agent_node_proto_depIdxs = []int32{
	0, // 0: agent.AgentNodeService.DeployNodeCompose:input_type -> agent.DeployNodeComposeRequest
	2, // 1: agent.AgentNodeService.StopNodeCompose:input_type -> agent.StopNodeComposeRequest
	3, // 2: agent.AgentNodeService.GetNodeStatus:input_type -> agent.GetNodeStatusRequest
	5, // 3: agent.AgentNodeService.GetNodeLogs:input_type -> agent.GetNodeLogsRequest
	1, // 4: agent.AgentNodeService.DeployNodeCompose:output_type -> agent.DeployNodeComposeResponse
	7, // 5: agent.AgentNodeService.StopNodeCompose:output_type -> common.MessageResponse
	4, // 6: agent.AgentNodeService.GetNodeStatus:output_type -> agent.GetNodeStatusResponse
	6, // 7: agent.AgentNodeService.GetNodeLogs:output_type -> agent.NodeLogResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_node_proto_init() }
func file_agent_node_proto_init() {
	if File_agent_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_node_proto_rawDesc), len(file_agent_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_node_proto_goTypes,
		DependencyIndexes: file_agent_node_proto_depIdxs,
		MessageInfos:      file_agent_node_proto_msgTypes,
	}.Build()
	File_agent_node_proto = out.File
	file_agent_node_proto_goTypes = nil
	file_agent_node_proto_depIdxs = nil
}
