// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: frontend/server.proto

package frontend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_UNSPECIFIED       StatusCode = 0
	StatusCode_OK                StatusCode = 200
	StatusCode_CREATED           StatusCode = 201
	StatusCode_NOT_FOUND         StatusCode = 404
	StatusCode_INTERNAL_ERROR    StatusCode = 500
	StatusCode_BAD_REQUEST       StatusCode = 400
	StatusCode_VALIDATION_FAILED StatusCode = 402
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:   "UNSPECIFIED",
		200: "OK",
		201: "CREATED",
		404: "NOT_FOUND",
		500: "INTERNAL_ERROR",
		400: "BAD_REQUEST",
		402: "VALIDATION_FAILED",
	}
	StatusCode_value = map[string]int32{
		"UNSPECIFIED":       0,
		"OK":                200,
		"CREATED":           201,
		"NOT_FOUND":         404,
		"INTERNAL_ERROR":    500,
		"BAD_REQUEST":       400,
		"VALIDATION_FAILED": 402,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_frontend_server_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_frontend_server_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_frontend_server_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_frontend_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_frontend_server_proto_rawDescGZIP(), []int{0}
}

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_frontend_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_frontend_server_proto_rawDescGZIP(), []int{1}
}

func (x *Id) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=frontend.StatusCode" json:"status,omitempty"`
	Server        *Server                `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Error         *string                `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	mi := &file_frontend_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_frontend_server_proto_rawDescGZIP(), []int{2}
}

func (x *ServerResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_UNSPECIFIED
}

func (x *ServerResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ServerResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ServerResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=frontend.StatusCode" json:"status,omitempty"`
	Servers       []*Server              `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Error         *string                `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServersResponse) Reset() {
	*x = ServersResponse{}
	mi := &file_frontend_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersResponse) ProtoMessage() {}

func (x *ServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersResponse.ProtoReflect.Descriptor instead.
func (*ServersResponse) Descriptor() ([]byte, []int) {
	return file_frontend_server_proto_rawDescGZIP(), []int{3}
}

func (x *ServersResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_UNSPECIFIED
}

func (x *ServersResponse) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ServersResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ServersResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Credential    *ServerCredential      `protobuf:"bytes,6,opt,name=credential,proto3" json:"credential,omitempty"`
	IsRoot        int32                  `protobuf:"varint,7,opt,name=isRoot,proto3" json:"isRoot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_frontend_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_frontend_server_proto_rawDescGZIP(), []int{4}
}

func (x *Server) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Server) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Server) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Server) GetCredential() *ServerCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *Server) GetIsRoot() int32 {
	if x != nil {
		return x.IsRoot
	}
	return 0
}

type ServerCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	SshKey        *string                `protobuf:"bytes,3,opt,name=sshKey,proto3,oneof" json:"sshKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCredential) Reset() {
	*x = ServerCredential{}
	mi := &file_frontend_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCredential) ProtoMessage() {}

func (x *ServerCredential) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCredential.ProtoReflect.Descriptor instead.
func (*ServerCredential) Descriptor() ([]byte, []int) {
	return file_frontend_server_proto_rawDescGZIP(), []int{5}
}

func (x *ServerCredential) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ServerCredential) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *ServerCredential) GetSshKey() string {
	if x != nil && x.SshKey != nil {
		return *x.SshKey
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=frontend.StatusCode" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_frontend_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_frontend_server_proto_rawDescGZIP(), []int{6}
}

func (x *MessageResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_UNSPECIFIED
}

func (x *MessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_frontend_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_frontend_server_proto_rawDescGZIP(), []int{7}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_frontend_server_proto protoreflect.FileDescriptor

const file_frontend_server_proto_rawDesc = "" +
	"\n" +
	"\x15frontend/server.proto\x12\bfrontend\"\a\n" +
	"\x05Empty\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc0\x01\n" +
	"\x0eServerResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.frontend.StatusCodeR\x06status\x12(\n" +
	"\x06server\x18\x02 \x01(\v2\x10.frontend.ServerR\x06server\x121\n" +
	"\x06errors\x18\x03 \x03(\v2\x19.frontend.ValidationErrorR\x06errors\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xc3\x01\n" +
	"\x0fServersResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.frontend.StatusCodeR\x06status\x12*\n" +
	"\aservers\x18\x02 \x03(\v2\x10.frontend.ServerR\aservers\x121\n" +
	"\x06errors\x18\x03 \x03(\v2\x19.frontend.ValidationErrorR\x06errors\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xce\x01\n" +
	"\x06Server\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tipAddress\x18\x03 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12:\n" +
	"\n" +
	"credential\x18\x06 \x01(\v2\x1a.frontend.ServerCredentialR\n" +
	"credential\x12\x16\n" +
	"\x06isRoot\x18\a \x01(\x05R\x06isRoot\"\x84\x01\n" +
	"\x10ServerCredential\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tH\x00R\bpassword\x88\x01\x01\x12\x1b\n" +
	"\x06sshKey\x18\x03 \x01(\tH\x01R\x06sshKey\x88\x01\x01B\v\n" +
	"\t_passwordB\t\n" +
	"\a_sshKey\"Y\n" +
	"\x0fMessageResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.frontend.StatusCodeR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x83\x01\n" +
	"\n" +
	"StatusCode\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\a\n" +
	"\x02OK\x10\xc8\x01\x12\f\n" +
	"\aCREATED\x10\xc9\x01\x12\x0e\n" +
	"\tNOT_FOUND\x10\x94\x03\x12\x13\n" +
	"\x0eINTERNAL_ERROR\x10\xf4\x03\x12\x10\n" +
	"\vBAD_REQUEST\x10\x90\x03\x12\x16\n" +
	"\x11VALIDATION_FAILED\x10\x92\x032\x90\x02\n" +
	"\rServerService\x124\n" +
	"\x06Create\x12\x10.frontend.Server\x1a\x18.frontend.ServerResponse\x12-\n" +
	"\x03Get\x12\f.frontend.Id\x1a\x18.frontend.ServerResponse\x121\n" +
	"\x03All\x12\x0f.frontend.Empty\x1a\x19.frontend.ServersResponse\x124\n" +
	"\x06Update\x12\x10.frontend.Server\x1a\x18.frontend.ServerResponse\x121\n" +
	"\x06Delete\x12\f.frontend.Id\x1a\x19.frontend.MessageResponseB\x1fZ\x1dinternal/infra/proto/frontendb\x06proto3"

var (
	file_frontend_server_proto_rawDescOnce sync.Once
	file_frontend_server_proto_rawDescData []byte
)

func file_frontend_server_proto_rawDescGZIP() []byte {
	file_frontend_server_proto_rawDescOnce.Do(func() {
		file_frontend_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frontend_server_proto_rawDesc), len(file_frontend_server_proto_rawDesc)))
	})
	return file_frontend_server_proto_rawDescData
}

var file_frontend_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_frontend_server_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_frontend_server_proto_goTypes = []any{
	(StatusCode)(0),          // 0: frontend.StatusCode
	(*Empty)(nil),            // 1: frontend.Empty
	(*Id)(nil),               // 2: frontend.Id
	(*ServerResponse)(nil),   // 3: frontend.ServerResponse
	(*ServersResponse)(nil),  // 4: frontend.ServersResponse
	(*Server)(nil),           // 5: frontend.Server
	(*ServerCredential)(nil), // 6: frontend.ServerCredential
	(*MessageResponse)(nil),  // 7: frontend.MessageResponse
	(*ValidationError)(nil),  // 8: frontend.ValidationError
}
var file_frontend_server_proto_depIdxs = []int32{
	0,  // 0: frontend.ServerResponse.status:type_name -> frontend.StatusCode
	5,  // 1: frontend.ServerResponse.server:type_name -> frontend.Server
	8,  // 2: frontend.ServerResponse.errors:type_name -> frontend.ValidationError
	0,  // 3: frontend.ServersResponse.status:type_name -> frontend.StatusCode
	5,  // 4: frontend.ServersResponse.servers:type_name -> frontend.Server
	8,  // 5: frontend.ServersResponse.errors:type_name -> frontend.ValidationError
	6,  // 6: frontend.Server.credential:type_name -> frontend.ServerCredential
	0,  // 7: frontend.MessageResponse.status:type_name -> frontend.StatusCode
	5,  // 8: frontend.ServerService.Create:input_type -> frontend.Server
	2,  // 9: frontend.ServerService.Get:input_type -> frontend.Id
	1,  // 10: frontend.ServerService.All:input_type -> frontend.Empty
	5,  // 11: frontend.ServerService.Update:input_type -> frontend.Server
	2,  // 12: frontend.ServerService.Delete:input_type -> frontend.Id
	3,  // 13: frontend.ServerService.Create:output_type -> frontend.ServerResponse
	3,  // 14: frontend.ServerService.Get:output_type -> frontend.ServerResponse
	4,  // 15: frontend.ServerService.All:output_type -> frontend.ServersResponse
	3,  // 16: frontend.ServerService.Update:output_type -> frontend.ServerResponse
	7,  // 17: frontend.ServerService.Delete:output_type -> frontend.MessageResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_frontend_server_proto_init() }
func file_frontend_server_proto_init() {
	if File_frontend_server_proto != nil {
		return
	}
	file_frontend_server_proto_msgTypes[2].OneofWrappers = []any{}
	file_frontend_server_proto_msgTypes[3].OneofWrappers = []any{}
	file_frontend_server_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frontend_server_proto_rawDesc), len(file_frontend_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_frontend_server_proto_goTypes,
		DependencyIndexes: file_frontend_server_proto_depIdxs,
		EnumInfos:         file_frontend_server_proto_enumTypes,
		MessageInfos:      file_frontend_server_proto_msgTypes,
	}.Build()
	File_frontend_server_proto = out.File
	file_frontend_server_proto_goTypes = nil
	file_frontend_server_proto_depIdxs = nil
}
