// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: controlplane/backup.proto

package controlplane

import (
	context "context"
	common "github.com/zhinea/sylix/internal/infra/proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackupStorageService_Create_FullMethodName         = "/controlplane.BackupStorageService/Create"
	BackupStorageService_Get_FullMethodName            = "/controlplane.BackupStorageService/Get"
	BackupStorageService_All_FullMethodName            = "/controlplane.BackupStorageService/All"
	BackupStorageService_Update_FullMethodName         = "/controlplane.BackupStorageService/Update"
	BackupStorageService_Delete_FullMethodName         = "/controlplane.BackupStorageService/Delete"
	BackupStorageService_TestConnection_FullMethodName = "/controlplane.BackupStorageService/TestConnection"
)

// BackupStorageServiceClient is the client API for BackupStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackupStorageServiceClient interface {
	Create(ctx context.Context, in *BackupStorage, opts ...grpc.CallOption) (*BackupStorageResponse, error)
	Get(ctx context.Context, in *BackupStorageId, opts ...grpc.CallOption) (*BackupStorageResponse, error)
	All(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*BackupStoragesResponse, error)
	Update(ctx context.Context, in *BackupStorage, opts ...grpc.CallOption) (*BackupStorageResponse, error)
	Delete(ctx context.Context, in *BackupStorageId, opts ...grpc.CallOption) (*BackupMessageResponse, error)
	TestConnection(ctx context.Context, in *BackupStorage, opts ...grpc.CallOption) (*BackupMessageResponse, error)
}

type backupStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackupStorageServiceClient(cc grpc.ClientConnInterface) BackupStorageServiceClient {
	return &backupStorageServiceClient{cc}
}

func (c *backupStorageServiceClient) Create(ctx context.Context, in *BackupStorage, opts ...grpc.CallOption) (*BackupStorageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupStorageResponse)
	err := c.cc.Invoke(ctx, BackupStorageService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupStorageServiceClient) Get(ctx context.Context, in *BackupStorageId, opts ...grpc.CallOption) (*BackupStorageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupStorageResponse)
	err := c.cc.Invoke(ctx, BackupStorageService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupStorageServiceClient) All(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*BackupStoragesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupStoragesResponse)
	err := c.cc.Invoke(ctx, BackupStorageService_All_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupStorageServiceClient) Update(ctx context.Context, in *BackupStorage, opts ...grpc.CallOption) (*BackupStorageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupStorageResponse)
	err := c.cc.Invoke(ctx, BackupStorageService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupStorageServiceClient) Delete(ctx context.Context, in *BackupStorageId, opts ...grpc.CallOption) (*BackupMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupMessageResponse)
	err := c.cc.Invoke(ctx, BackupStorageService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupStorageServiceClient) TestConnection(ctx context.Context, in *BackupStorage, opts ...grpc.CallOption) (*BackupMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupMessageResponse)
	err := c.cc.Invoke(ctx, BackupStorageService_TestConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackupStorageServiceServer is the server API for BackupStorageService service.
// All implementations must embed UnimplementedBackupStorageServiceServer
// for forward compatibility.
type BackupStorageServiceServer interface {
	Create(context.Context, *BackupStorage) (*BackupStorageResponse, error)
	Get(context.Context, *BackupStorageId) (*BackupStorageResponse, error)
	All(context.Context, *common.Empty) (*BackupStoragesResponse, error)
	Update(context.Context, *BackupStorage) (*BackupStorageResponse, error)
	Delete(context.Context, *BackupStorageId) (*BackupMessageResponse, error)
	TestConnection(context.Context, *BackupStorage) (*BackupMessageResponse, error)
	mustEmbedUnimplementedBackupStorageServiceServer()
}

// UnimplementedBackupStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackupStorageServiceServer struct{}

func (UnimplementedBackupStorageServiceServer) Create(context.Context, *BackupStorage) (*BackupStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBackupStorageServiceServer) Get(context.Context, *BackupStorageId) (*BackupStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBackupStorageServiceServer) All(context.Context, *common.Empty) (*BackupStoragesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method All not implemented")
}
func (UnimplementedBackupStorageServiceServer) Update(context.Context, *BackupStorage) (*BackupStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedBackupStorageServiceServer) Delete(context.Context, *BackupStorageId) (*BackupMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBackupStorageServiceServer) TestConnection(context.Context, *BackupStorage) (*BackupMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestConnection not implemented")
}
func (UnimplementedBackupStorageServiceServer) mustEmbedUnimplementedBackupStorageServiceServer() {}
func (UnimplementedBackupStorageServiceServer) testEmbeddedByValue()                              {}

// UnsafeBackupStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackupStorageServiceServer will
// result in compilation errors.
type UnsafeBackupStorageServiceServer interface {
	mustEmbedUnimplementedBackupStorageServiceServer()
}

func RegisterBackupStorageServiceServer(s grpc.ServiceRegistrar, srv BackupStorageServiceServer) {
	// If the following call pancis, it indicates UnimplementedBackupStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackupStorageService_ServiceDesc, srv)
}

func _BackupStorageService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupStorage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupStorageServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupStorageService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupStorageServiceServer).Create(ctx, req.(*BackupStorage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupStorageService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupStorageId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupStorageServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupStorageService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupStorageServiceServer).Get(ctx, req.(*BackupStorageId))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupStorageService_All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupStorageServiceServer).All(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupStorageService_All_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupStorageServiceServer).All(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupStorageService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupStorage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupStorageServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupStorageService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupStorageServiceServer).Update(ctx, req.(*BackupStorage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupStorageService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupStorageId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupStorageServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupStorageService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupStorageServiceServer).Delete(ctx, req.(*BackupStorageId))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupStorageService_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupStorage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupStorageServiceServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupStorageService_TestConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupStorageServiceServer).TestConnection(ctx, req.(*BackupStorage))
	}
	return interceptor(ctx, in, info, handler)
}

// BackupStorageService_ServiceDesc is the grpc.ServiceDesc for BackupStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackupStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controlplane.BackupStorageService",
	HandlerType: (*BackupStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BackupStorageService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BackupStorageService_Get_Handler,
		},
		{
			MethodName: "All",
			Handler:    _BackupStorageService_All_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BackupStorageService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BackupStorageService_Delete_Handler,
		},
		{
			MethodName: "TestConnection",
			Handler:    _BackupStorageService_TestConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controlplane/backup.proto",
}
