// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: controlplane/backup.proto

package controlplane

import (
	common "github.com/zhinea/sylix/internal/infra/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackupStatusCode int32

const (
	BackupStatusCode_BACKUP_UNSPECIFIED    BackupStatusCode = 0
	BackupStatusCode_BACKUP_OK             BackupStatusCode = 200
	BackupStatusCode_BACKUP_CREATED        BackupStatusCode = 201
	BackupStatusCode_BACKUP_NOT_FOUND      BackupStatusCode = 404
	BackupStatusCode_BACKUP_INTERNAL_ERROR BackupStatusCode = 500
	BackupStatusCode_BACKUP_BAD_REQUEST    BackupStatusCode = 400
)

// Enum value maps for BackupStatusCode.
var (
	BackupStatusCode_name = map[int32]string{
		0:   "BACKUP_UNSPECIFIED",
		200: "BACKUP_OK",
		201: "BACKUP_CREATED",
		404: "BACKUP_NOT_FOUND",
		500: "BACKUP_INTERNAL_ERROR",
		400: "BACKUP_BAD_REQUEST",
	}
	BackupStatusCode_value = map[string]int32{
		"BACKUP_UNSPECIFIED":    0,
		"BACKUP_OK":             200,
		"BACKUP_CREATED":        201,
		"BACKUP_NOT_FOUND":      404,
		"BACKUP_INTERNAL_ERROR": 500,
		"BACKUP_BAD_REQUEST":    400,
	}
)

func (x BackupStatusCode) Enum() *BackupStatusCode {
	p := new(BackupStatusCode)
	*p = x
	return p
}

func (x BackupStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackupStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_backup_proto_enumTypes[0].Descriptor()
}

func (BackupStatusCode) Type() protoreflect.EnumType {
	return &file_controlplane_backup_proto_enumTypes[0]
}

func (x BackupStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackupStatusCode.Descriptor instead.
func (BackupStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_backup_proto_rawDescGZIP(), []int{0}
}

type BackupStorageId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupStorageId) Reset() {
	*x = BackupStorageId{}
	mi := &file_controlplane_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupStorageId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupStorageId) ProtoMessage() {}

func (x *BackupStorageId) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupStorageId.ProtoReflect.Descriptor instead.
func (*BackupStorageId) Descriptor() ([]byte, []int) {
	return file_controlplane_backup_proto_rawDescGZIP(), []int{0}
}

func (x *BackupStorageId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BackupMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        BackupStatusCode       `protobuf:"varint,1,opt,name=status,proto3,enum=controlplane.BackupStatusCode" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupMessageResponse) Reset() {
	*x = BackupMessageResponse{}
	mi := &file_controlplane_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupMessageResponse) ProtoMessage() {}

func (x *BackupMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupMessageResponse.ProtoReflect.Descriptor instead.
func (*BackupMessageResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_backup_proto_rawDescGZIP(), []int{1}
}

func (x *BackupMessageResponse) GetStatus() BackupStatusCode {
	if x != nil {
		return x.Status
	}
	return BackupStatusCode_BACKUP_UNSPECIFIED
}

func (x *BackupMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BackupStorage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Bucket        string                 `protobuf:"bytes,5,opt,name=bucket,proto3" json:"bucket,omitempty"`
	AccessKey     string                 `protobuf:"bytes,6,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,7,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // CONNECTED, ERROR
	ErrorMessage  string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupStorage) Reset() {
	*x = BackupStorage{}
	mi := &file_controlplane_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupStorage) ProtoMessage() {}

func (x *BackupStorage) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupStorage.ProtoReflect.Descriptor instead.
func (*BackupStorage) Descriptor() ([]byte, []int) {
	return file_controlplane_backup_proto_rawDescGZIP(), []int{2}
}

func (x *BackupStorage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BackupStorage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupStorage) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *BackupStorage) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *BackupStorage) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *BackupStorage) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *BackupStorage) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *BackupStorage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BackupStorage) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type BackupStorageResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          *BackupStorage            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status        BackupStatusCode          `protobuf:"varint,2,opt,name=status,proto3,enum=controlplane.BackupStatusCode" json:"status,omitempty"`
	Errors        []*common.ValidationError `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Error         *string                   `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupStorageResponse) Reset() {
	*x = BackupStorageResponse{}
	mi := &file_controlplane_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupStorageResponse) ProtoMessage() {}

func (x *BackupStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupStorageResponse.ProtoReflect.Descriptor instead.
func (*BackupStorageResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_backup_proto_rawDescGZIP(), []int{3}
}

func (x *BackupStorageResponse) GetData() *BackupStorage {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BackupStorageResponse) GetStatus() BackupStatusCode {
	if x != nil {
		return x.Status
	}
	return BackupStatusCode_BACKUP_UNSPECIFIED
}

func (x *BackupStorageResponse) GetErrors() []*common.ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BackupStorageResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type BackupStoragesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*BackupStorage       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Status        BackupStatusCode       `protobuf:"varint,2,opt,name=status,proto3,enum=controlplane.BackupStatusCode" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupStoragesResponse) Reset() {
	*x = BackupStoragesResponse{}
	mi := &file_controlplane_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupStoragesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupStoragesResponse) ProtoMessage() {}

func (x *BackupStoragesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupStoragesResponse.ProtoReflect.Descriptor instead.
func (*BackupStoragesResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_backup_proto_rawDescGZIP(), []int{4}
}

func (x *BackupStoragesResponse) GetData() []*BackupStorage {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BackupStoragesResponse) GetStatus() BackupStatusCode {
	if x != nil {
		return x.Status
	}
	return BackupStatusCode_BACKUP_UNSPECIFIED
}

var File_controlplane_backup_proto protoreflect.FileDescriptor

const file_controlplane_backup_proto_rawDesc = "" +
	"\n" +
	"\x19controlplane/backup.proto\x12\fcontrolplane\x1a\x17common/validation.proto\x1a\x13common/common.proto\"!\n" +
	"\x0fBackupStorageId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"i\n" +
	"\x15BackupMessageResponse\x126\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1e.controlplane.BackupStatusCodeR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfa\x01\n" +
	"\rBackupStorage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x16\n" +
	"\x06bucket\x18\x05 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"access_key\x18\x06 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\a \x01(\tR\tsecretKey\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\"\xd6\x01\n" +
	"\x15BackupStorageResponse\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.controlplane.BackupStorageR\x04data\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.controlplane.BackupStatusCodeR\x06status\x12/\n" +
	"\x06errors\x18\x03 \x03(\v2\x17.common.ValidationErrorR\x06errors\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x81\x01\n" +
	"\x16BackupStoragesResponse\x12/\n" +
	"\x04data\x18\x01 \x03(\v2\x1b.controlplane.BackupStorageR\x04data\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.controlplane.BackupStatusCodeR\x06status*\x9b\x01\n" +
	"\x10BackupStatusCode\x12\x16\n" +
	"\x12BACKUP_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\tBACKUP_OK\x10\xc8\x01\x12\x13\n" +
	"\x0eBACKUP_CREATED\x10\xc9\x01\x12\x15\n" +
	"\x10BACKUP_NOT_FOUND\x10\x94\x03\x12\x1a\n" +
	"\x15BACKUP_INTERNAL_ERROR\x10\xf4\x03\x12\x17\n" +
	"\x12BACKUP_BAD_REQUEST\x10\x90\x032\xd7\x03\n" +
	"\x14BackupStorageService\x12J\n" +
	"\x06Create\x12\x1b.controlplane.BackupStorage\x1a#.controlplane.BackupStorageResponse\x12I\n" +
	"\x03Get\x12\x1d.controlplane.BackupStorageId\x1a#.controlplane.BackupStorageResponse\x12:\n" +
	"\x03All\x12\r.common.Empty\x1a$.controlplane.BackupStoragesResponse\x12J\n" +
	"\x06Update\x12\x1b.controlplane.BackupStorage\x1a#.controlplane.BackupStorageResponse\x12L\n" +
	"\x06Delete\x12\x1d.controlplane.BackupStorageId\x1a#.controlplane.BackupMessageResponse\x12R\n" +
	"\x0eTestConnection\x12\x1b.controlplane.BackupStorage\x1a#.controlplane.BackupMessageResponseB;Z9github.com/zhinea/sylix/internal/infra/proto/controlplaneb\x06proto3"

var (
	file_controlplane_backup_proto_rawDescOnce sync.Once
	file_controlplane_backup_proto_rawDescData []byte
)

func file_controlplane_backup_proto_rawDescGZIP() []byte {
	file_controlplane_backup_proto_rawDescOnce.Do(func() {
		file_controlplane_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_backup_proto_rawDesc), len(file_controlplane_backup_proto_rawDesc)))
	})
	return file_controlplane_backup_proto_rawDescData
}

var file_controlplane_backup_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controlplane_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_controlplane_backup_proto_goTypes = []any{
	(BackupStatusCode)(0),          // 0: controlplane.BackupStatusCode
	(*BackupStorageId)(nil),        // 1: controlplane.BackupStorageId
	(*BackupMessageResponse)(nil),  // 2: controlplane.BackupMessageResponse
	(*BackupStorage)(nil),          // 3: controlplane.BackupStorage
	(*BackupStorageResponse)(nil),  // 4: controlplane.BackupStorageResponse
	(*BackupStoragesResponse)(nil), // 5: controlplane.BackupStoragesResponse
	(*common.ValidationError)(nil), // 6: common.ValidationError
	(*common.Empty)(nil),           // 7: common.Empty
}
var file_controlplane_backup_proto_depIdxs = []int32{
	0,  // 0: controlplane.BackupMessageResponse.status:type_name -> controlplane.BackupStatusCode
	3,  // 1: controlplane.BackupStorageResponse.data:type_name -> controlplane.BackupStorage
	0,  // 2: controlplane.BackupStorageResponse.status:type_name -> controlplane.BackupStatusCode
	6,  // 3: controlplane.BackupStorageResponse.errors:type_name -> common.ValidationError
	3,  // 4: controlplane.BackupStoragesResponse.data:type_name -> controlplane.BackupStorage
	0,  // 5: controlplane.BackupStoragesResponse.status:type_name -> controlplane.BackupStatusCode
	3,  // 6: controlplane.BackupStorageService.Create:input_type -> controlplane.BackupStorage
	1,  // 7: controlplane.BackupStorageService.Get:input_type -> controlplane.BackupStorageId
	7,  // 8: controlplane.BackupStorageService.All:input_type -> common.Empty
	3,  // 9: controlplane.BackupStorageService.Update:input_type -> controlplane.BackupStorage
	1,  // 10: controlplane.BackupStorageService.Delete:input_type -> controlplane.BackupStorageId
	3,  // 11: controlplane.BackupStorageService.TestConnection:input_type -> controlplane.BackupStorage
	4,  // 12: controlplane.BackupStorageService.Create:output_type -> controlplane.BackupStorageResponse
	4,  // 13: controlplane.BackupStorageService.Get:output_type -> controlplane.BackupStorageResponse
	5,  // 14: controlplane.BackupStorageService.All:output_type -> controlplane.BackupStoragesResponse
	4,  // 15: controlplane.BackupStorageService.Update:output_type -> controlplane.BackupStorageResponse
	2,  // 16: controlplane.BackupStorageService.Delete:output_type -> controlplane.BackupMessageResponse
	2,  // 17: controlplane.BackupStorageService.TestConnection:output_type -> controlplane.BackupMessageResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_controlplane_backup_proto_init() }
func file_controlplane_backup_proto_init() {
	if File_controlplane_backup_proto != nil {
		return
	}
	file_controlplane_backup_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_backup_proto_rawDesc), len(file_controlplane_backup_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_backup_proto_goTypes,
		DependencyIndexes: file_controlplane_backup_proto_depIdxs,
		EnumInfos:         file_controlplane_backup_proto_enumTypes,
		MessageInfos:      file_controlplane_backup_proto_msgTypes,
	}.Build()
	File_controlplane_backup_proto = out.File
	file_controlplane_backup_proto_goTypes = nil
	file_controlplane_backup_proto_depIdxs = nil
}
