// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: controlplane/logs.proto

package controlplane

import (
	context "context"
	common "github.com/zhinea/sylix/internal/infra/proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogsService_GetSystemLogs_FullMethodName = "/controlplane.LogsService/GetSystemLogs"
	LogsService_ReadSystemLog_FullMethodName = "/controlplane.LogsService/ReadSystemLog"
	LogsService_GetServerLogs_FullMethodName = "/controlplane.LogsService/GetServerLogs"
	LogsService_ReadServerLog_FullMethodName = "/controlplane.LogsService/ReadServerLog"
)

// LogsServiceClient is the client API for LogsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogsServiceClient interface {
	GetSystemLogs(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*GetSystemLogsResponse, error)
	ReadSystemLog(ctx context.Context, in *ReadSystemLogRequest, opts ...grpc.CallOption) (*ReadSystemLogResponse, error)
	GetServerLogs(ctx context.Context, in *GetServerLogsRequest, opts ...grpc.CallOption) (*GetServerLogsResponse, error)
	ReadServerLog(ctx context.Context, in *ReadServerLogRequest, opts ...grpc.CallOption) (*ReadServerLogResponse, error)
}

type logsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogsServiceClient(cc grpc.ClientConnInterface) LogsServiceClient {
	return &logsServiceClient{cc}
}

func (c *logsServiceClient) GetSystemLogs(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*GetSystemLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSystemLogsResponse)
	err := c.cc.Invoke(ctx, LogsService_GetSystemLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logsServiceClient) ReadSystemLog(ctx context.Context, in *ReadSystemLogRequest, opts ...grpc.CallOption) (*ReadSystemLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadSystemLogResponse)
	err := c.cc.Invoke(ctx, LogsService_ReadSystemLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logsServiceClient) GetServerLogs(ctx context.Context, in *GetServerLogsRequest, opts ...grpc.CallOption) (*GetServerLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerLogsResponse)
	err := c.cc.Invoke(ctx, LogsService_GetServerLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logsServiceClient) ReadServerLog(ctx context.Context, in *ReadServerLogRequest, opts ...grpc.CallOption) (*ReadServerLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadServerLogResponse)
	err := c.cc.Invoke(ctx, LogsService_ReadServerLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogsServiceServer is the server API for LogsService service.
// All implementations must embed UnimplementedLogsServiceServer
// for forward compatibility.
type LogsServiceServer interface {
	GetSystemLogs(context.Context, *common.Empty) (*GetSystemLogsResponse, error)
	ReadSystemLog(context.Context, *ReadSystemLogRequest) (*ReadSystemLogResponse, error)
	GetServerLogs(context.Context, *GetServerLogsRequest) (*GetServerLogsResponse, error)
	ReadServerLog(context.Context, *ReadServerLogRequest) (*ReadServerLogResponse, error)
	mustEmbedUnimplementedLogsServiceServer()
}

// UnimplementedLogsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogsServiceServer struct{}

func (UnimplementedLogsServiceServer) GetSystemLogs(context.Context, *common.Empty) (*GetSystemLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemLogs not implemented")
}
func (UnimplementedLogsServiceServer) ReadSystemLog(context.Context, *ReadSystemLogRequest) (*ReadSystemLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadSystemLog not implemented")
}
func (UnimplementedLogsServiceServer) GetServerLogs(context.Context, *GetServerLogsRequest) (*GetServerLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerLogs not implemented")
}
func (UnimplementedLogsServiceServer) ReadServerLog(context.Context, *ReadServerLogRequest) (*ReadServerLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadServerLog not implemented")
}
func (UnimplementedLogsServiceServer) mustEmbedUnimplementedLogsServiceServer() {}
func (UnimplementedLogsServiceServer) testEmbeddedByValue()                     {}

// UnsafeLogsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogsServiceServer will
// result in compilation errors.
type UnsafeLogsServiceServer interface {
	mustEmbedUnimplementedLogsServiceServer()
}

func RegisterLogsServiceServer(s grpc.ServiceRegistrar, srv LogsServiceServer) {
	// If the following call pancis, it indicates UnimplementedLogsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogsService_ServiceDesc, srv)
}

func _LogsService_GetSystemLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogsServiceServer).GetSystemLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogsService_GetSystemLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogsServiceServer).GetSystemLogs(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogsService_ReadSystemLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSystemLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogsServiceServer).ReadSystemLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogsService_ReadSystemLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogsServiceServer).ReadSystemLog(ctx, req.(*ReadSystemLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogsService_GetServerLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogsServiceServer).GetServerLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogsService_GetServerLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogsServiceServer).GetServerLogs(ctx, req.(*GetServerLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogsService_ReadServerLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadServerLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogsServiceServer).ReadServerLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogsService_ReadServerLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogsServiceServer).ReadServerLog(ctx, req.(*ReadServerLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogsService_ServiceDesc is the grpc.ServiceDesc for LogsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controlplane.LogsService",
	HandlerType: (*LogsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemLogs",
			Handler:    _LogsService_GetSystemLogs_Handler,
		},
		{
			MethodName: "ReadSystemLog",
			Handler:    _LogsService_ReadSystemLog_Handler,
		},
		{
			MethodName: "GetServerLogs",
			Handler:    _LogsService_GetServerLogs_Handler,
		},
		{
			MethodName: "ReadServerLog",
			Handler:    _LogsService_ReadServerLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controlplane/logs.proto",
}
