// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: controlplane/node.proto

package controlplane

import (
	common "github.com/zhinea/sylix/internal/infra/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeGraph) Reset() {
	*x = NodeGraph{}
	mi := &file_controlplane_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeGraph) ProtoMessage() {}

func (x *NodeGraph) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeGraph.ProtoReflect.Descriptor instead.
func (*NodeGraph) Descriptor() ([]byte, []int) {
	return file_controlplane_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeGraph) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeGraph) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeGraph) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *NodeGraph) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *NodeGraph) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *NodeGraph) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // compute, pageserver, safekeeper, storage_broker
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Position      *NodePosition          `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Data          *NodeData              `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_controlplane_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_controlplane_node_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Node) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Node) GetPosition() *NodePosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Node) GetData() *NodeData {
	if x != nil {
		return x.Data
	}
	return nil
}

type NodePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePosition) Reset() {
	*x = NodePosition{}
	mi := &file_controlplane_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePosition) ProtoMessage() {}

func (x *NodePosition) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePosition.ProtoReflect.Descriptor instead.
func (*NodePosition) Descriptor() ([]byte, []int) {
	return file_controlplane_node_proto_rawDescGZIP(), []int{2}
}

func (x *NodePosition) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NodePosition) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type NodeData struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// Specific fields for different node types
	PgVersion       string `protobuf:"bytes,2,opt,name=pg_version,json=pgVersion,proto3" json:"pg_version,omitempty"`                     // compute
	PgPort          int32  `protobuf:"varint,3,opt,name=pg_port,json=pgPort,proto3" json:"pg_port,omitempty"`                             // compute
	ExposeInternet  bool   `protobuf:"varint,4,opt,name=expose_internet,json=exposeInternet,proto3" json:"expose_internet,omitempty"`     // compute
	BackupStorageId string `protobuf:"bytes,5,opt,name=backup_storage_id,json=backupStorageId,proto3" json:"backup_storage_id,omitempty"` // pageserver, safekeeper
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeData) Reset() {
	*x = NodeData{}
	mi := &file_controlplane_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeData) ProtoMessage() {}

func (x *NodeData) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeData.ProtoReflect.Descriptor instead.
func (*NodeData) Descriptor() ([]byte, []int) {
	return file_controlplane_node_proto_rawDescGZIP(), []int{3}
}

func (x *NodeData) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *NodeData) GetPgVersion() string {
	if x != nil {
		return x.PgVersion
	}
	return ""
}

func (x *NodeData) GetPgPort() int32 {
	if x != nil {
		return x.PgPort
	}
	return 0
}

func (x *NodeData) GetExposeInternet() bool {
	if x != nil {
		return x.ExposeInternet
	}
	return false
}

func (x *NodeData) GetBackupStorageId() string {
	if x != nil {
		return x.BackupStorageId
	}
	return ""
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	SourceHandle  string                 `protobuf:"bytes,4,opt,name=source_handle,json=sourceHandle,proto3" json:"source_handle,omitempty"`
	TargetHandle  string                 `protobuf:"bytes,5,opt,name=target_handle,json=targetHandle,proto3" json:"target_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_controlplane_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_controlplane_node_proto_rawDescGZIP(), []int{4}
}

func (x *Edge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Edge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Edge) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Edge) GetSourceHandle() string {
	if x != nil {
		return x.SourceHandle
	}
	return ""
}

func (x *Edge) GetTargetHandle() string {
	if x != nil {
		return x.TargetHandle
	}
	return ""
}

type CreateNodeGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,3,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeGraphRequest) Reset() {
	*x = CreateNodeGraphRequest{}
	mi := &file_controlplane_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeGraphRequest) ProtoMessage() {}

func (x *CreateNodeGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeGraphRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeGraphRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_node_proto_rawDescGZIP(), []int{5}
}

func (x *CreateNodeGraphRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNodeGraphRequest) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *CreateNodeGraphRequest) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type GetNodeGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeGraphRequest) Reset() {
	*x = GetNodeGraphRequest{}
	mi := &file_controlplane_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeGraphRequest) ProtoMessage() {}

func (x *GetNodeGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeGraphRequest.ProtoReflect.Descriptor instead.
func (*GetNodeGraphRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_node_proto_rawDescGZIP(), []int{6}
}

func (x *GetNodeGraphRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateNodeGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeGraphRequest) Reset() {
	*x = UpdateNodeGraphRequest{}
	mi := &file_controlplane_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeGraphRequest) ProtoMessage() {}

func (x *UpdateNodeGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeGraphRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeGraphRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_node_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateNodeGraphRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateNodeGraphRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateNodeGraphRequest) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *UpdateNodeGraphRequest) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type DeleteNodeGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeGraphRequest) Reset() {
	*x = DeleteNodeGraphRequest{}
	mi := &file_controlplane_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeGraphRequest) ProtoMessage() {}

func (x *DeleteNodeGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeGraphRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeGraphRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_node_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteNodeGraphRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeployNodeGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployNodeGraphRequest) Reset() {
	*x = DeployNodeGraphRequest{}
	mi := &file_controlplane_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployNodeGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployNodeGraphRequest) ProtoMessage() {}

func (x *DeployNodeGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployNodeGraphRequest.ProtoReflect.Descriptor instead.
func (*DeployNodeGraphRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_node_proto_rawDescGZIP(), []int{9}
}

func (x *DeployNodeGraphRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetNodeGraphStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeGraphStatusRequest) Reset() {
	*x = GetNodeGraphStatusRequest{}
	mi := &file_controlplane_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeGraphStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeGraphStatusRequest) ProtoMessage() {}

func (x *GetNodeGraphStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeGraphStatusRequest.ProtoReflect.Descriptor instead.
func (*GetNodeGraphStatusRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_node_proto_rawDescGZIP(), []int{10}
}

func (x *GetNodeGraphStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetNodeGraphStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                                                                                           // DEPLOYING, RUNNING, STOPPED, ERROR
	NodeStatuses  map[string]string      `protobuf:"bytes,2,rep,name=node_statuses,json=nodeStatuses,proto3" json:"node_statuses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key: node_id, value: status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeGraphStatusResponse) Reset() {
	*x = GetNodeGraphStatusResponse{}
	mi := &file_controlplane_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeGraphStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeGraphStatusResponse) ProtoMessage() {}

func (x *GetNodeGraphStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeGraphStatusResponse.ProtoReflect.Descriptor instead.
func (*GetNodeGraphStatusResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_node_proto_rawDescGZIP(), []int{11}
}

func (x *GetNodeGraphStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetNodeGraphStatusResponse) GetNodeStatuses() map[string]string {
	if x != nil {
		return x.NodeStatuses
	}
	return nil
}

type GetDeploymentLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Optional: filter by specific node in the graph
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentLogsRequest) Reset() {
	*x = GetDeploymentLogsRequest{}
	mi := &file_controlplane_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentLogsRequest) ProtoMessage() {}

func (x *GetDeploymentLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentLogsRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentLogsRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_node_proto_rawDescGZIP(), []int{12}
}

func (x *GetDeploymentLogsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDeploymentLogsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetDeploymentLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []string               `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentLogsResponse) Reset() {
	*x = GetDeploymentLogsResponse{}
	mi := &file_controlplane_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentLogsResponse) ProtoMessage() {}

func (x *GetDeploymentLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentLogsResponse.ProtoReflect.Descriptor instead.
func (*GetDeploymentLogsResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_node_proto_rawDescGZIP(), []int{13}
}

func (x *GetDeploymentLogsResponse) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

type NodeGraphResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        common.StatusCode         `protobuf:"varint,1,opt,name=status,proto3,enum=common.StatusCode" json:"status,omitempty"`
	Graph         *NodeGraph                `protobuf:"bytes,2,opt,name=graph,proto3" json:"graph,omitempty"`
	Errors        []*common.ValidationError `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Error         string                    `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeGraphResponse) Reset() {
	*x = NodeGraphResponse{}
	mi := &file_controlplane_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeGraphResponse) ProtoMessage() {}

func (x *NodeGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeGraphResponse.ProtoReflect.Descriptor instead.
func (*NodeGraphResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_node_proto_rawDescGZIP(), []int{14}
}

func (x *NodeGraphResponse) GetStatus() common.StatusCode {
	if x != nil {
		return x.Status
	}
	return common.StatusCode(0)
}

func (x *NodeGraphResponse) GetGraph() *NodeGraph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *NodeGraphResponse) GetErrors() []*common.ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *NodeGraphResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_controlplane_node_proto protoreflect.FileDescriptor

const file_controlplane_node_proto_rawDesc = "" +
	"\n" +
	"\x17controlplane/node.proto\x12\fcontrolplane\x1a\x17common/validation.proto\x1a\x13common/common.proto\"\xc1\x01\n" +
	"\tNodeGraph\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x05nodes\x18\x03 \x03(\v2\x12.controlplane.NodeR\x05nodes\x12(\n" +
	"\x05edges\x18\x04 \x03(\v2\x12.controlplane.EdgeR\x05edges\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xa4\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x126\n" +
	"\bposition\x18\x04 \x01(\v2\x1a.controlplane.NodePositionR\bposition\x12*\n" +
	"\x04data\x18\x05 \x01(\v2\x16.controlplane.NodeDataR\x04data\"*\n" +
	"\fNodePosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"\xb4\x01\n" +
	"\bNodeData\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"pg_version\x18\x02 \x01(\tR\tpgVersion\x12\x17\n" +
	"\apg_port\x18\x03 \x01(\x05R\x06pgPort\x12'\n" +
	"\x0fexpose_internet\x18\x04 \x01(\bR\x0eexposeInternet\x12*\n" +
	"\x11backup_storage_id\x18\x05 \x01(\tR\x0fbackupStorageId\"\x90\x01\n" +
	"\x04Edge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12#\n" +
	"\rsource_handle\x18\x04 \x01(\tR\fsourceHandle\x12#\n" +
	"\rtarget_handle\x18\x05 \x01(\tR\ftargetHandle\"\x80\x01\n" +
	"\x16CreateNodeGraphRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x05nodes\x18\x02 \x03(\v2\x12.controlplane.NodeR\x05nodes\x12(\n" +
	"\x05edges\x18\x03 \x03(\v2\x12.controlplane.EdgeR\x05edges\"%\n" +
	"\x13GetNodeGraphRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x90\x01\n" +
	"\x16UpdateNodeGraphRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x05nodes\x18\x03 \x03(\v2\x12.controlplane.NodeR\x05nodes\x12(\n" +
	"\x05edges\x18\x04 \x03(\v2\x12.controlplane.EdgeR\x05edges\"(\n" +
	"\x16DeleteNodeGraphRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x16DeployNodeGraphRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x19GetNodeGraphStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd6\x01\n" +
	"\x1aGetNodeGraphStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12_\n" +
	"\rnode_statuses\x18\x02 \x03(\v2:.controlplane.GetNodeGraphStatusResponse.NodeStatusesEntryR\fnodeStatuses\x1a?\n" +
	"\x11NodeStatusesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x18GetDeploymentLogsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"/\n" +
	"\x19GetDeploymentLogsResponse\x12\x12\n" +
	"\x04logs\x18\x01 \x03(\tR\x04logs\"\xb5\x01\n" +
	"\x11NodeGraphResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.common.StatusCodeR\x06status\x12-\n" +
	"\x05graph\x18\x02 \x01(\v2\x17.controlplane.NodeGraphR\x05graph\x12/\n" +
	"\x06errors\x18\x03 \x03(\v2\x17.common.ValidationErrorR\x06errors\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\x88\x05\n" +
	"\vNodeService\x12X\n" +
	"\x0fCreateNodeGraph\x12$.controlplane.CreateNodeGraphRequest\x1a\x1f.controlplane.NodeGraphResponse\x12R\n" +
	"\fGetNodeGraph\x12!.controlplane.GetNodeGraphRequest\x1a\x1f.controlplane.NodeGraphResponse\x12X\n" +
	"\x0fUpdateNodeGraph\x12$.controlplane.UpdateNodeGraphRequest\x1a\x1f.controlplane.NodeGraphResponse\x12P\n" +
	"\x0fDeleteNodeGraph\x12$.controlplane.DeleteNodeGraphRequest\x1a\x17.common.MessageResponse\x12P\n" +
	"\x0fDeployNodeGraph\x12$.controlplane.DeployNodeGraphRequest\x1a\x17.common.MessageResponse\x12g\n" +
	"\x12GetNodeGraphStatus\x12'.controlplane.GetNodeGraphStatusRequest\x1a(.controlplane.GetNodeGraphStatusResponse\x12d\n" +
	"\x11GetDeploymentLogs\x12&.controlplane.GetDeploymentLogsRequest\x1a'.controlplane.GetDeploymentLogsResponseB;Z9github.com/zhinea/sylix/internal/infra/proto/controlplaneb\x06proto3"

var (
	file_controlplane_node_proto_rawDescOnce sync.Once
	file_controlplane_node_proto_rawDescData []byte
)

func file_controlplane_node_proto_rawDescGZIP() []byte {
	file_controlplane_node_proto_rawDescOnce.Do(func() {
		file_controlplane_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_node_proto_rawDesc), len(file_controlplane_node_proto_rawDesc)))
	})
	return file_controlplane_node_proto_rawDescData
}

var file_controlplane_node_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_controlplane_node_proto_goTypes = []any{
	(*NodeGraph)(nil),                  // 0: controlplane.NodeGraph
	(*Node)(nil),                       // 1: controlplane.Node
	(*NodePosition)(nil),               // 2: controlplane.NodePosition
	(*NodeData)(nil),                   // 3: controlplane.NodeData
	(*Edge)(nil),                       // 4: controlplane.Edge
	(*CreateNodeGraphRequest)(nil),     // 5: controlplane.CreateNodeGraphRequest
	(*GetNodeGraphRequest)(nil),        // 6: controlplane.GetNodeGraphRequest
	(*UpdateNodeGraphRequest)(nil),     // 7: controlplane.UpdateNodeGraphRequest
	(*DeleteNodeGraphRequest)(nil),     // 8: controlplane.DeleteNodeGraphRequest
	(*DeployNodeGraphRequest)(nil),     // 9: controlplane.DeployNodeGraphRequest
	(*GetNodeGraphStatusRequest)(nil),  // 10: controlplane.GetNodeGraphStatusRequest
	(*GetNodeGraphStatusResponse)(nil), // 11: controlplane.GetNodeGraphStatusResponse
	(*GetDeploymentLogsRequest)(nil),   // 12: controlplane.GetDeploymentLogsRequest
	(*GetDeploymentLogsResponse)(nil),  // 13: controlplane.GetDeploymentLogsResponse
	(*NodeGraphResponse)(nil),          // 14: controlplane.NodeGraphResponse
	nil,                                // 15: controlplane.GetNodeGraphStatusResponse.NodeStatusesEntry
	(common.StatusCode)(0),             // 16: common.StatusCode
	(*common.ValidationError)(nil),     // 17: common.ValidationError
	(*common.MessageResponse)(nil),     // 18: common.MessageResponse
}
var file_controlplane_node_proto_depIdxs = []int32{
	1,  // 0: controlplane.NodeGraph.nodes:type_name -> controlplane.Node
	4,  // 1: controlplane.NodeGraph.edges:type_name -> controlplane.Edge
	2,  // 2: controlplane.Node.position:type_name -> controlplane.NodePosition
	3,  // 3: controlplane.Node.data:type_name -> controlplane.NodeData
	1,  // 4: controlplane.CreateNodeGraphRequest.nodes:type_name -> controlplane.Node
	4,  // 5: controlplane.CreateNodeGraphRequest.edges:type_name -> controlplane.Edge
	1,  // 6: controlplane.UpdateNodeGraphRequest.nodes:type_name -> controlplane.Node
	4,  // 7: controlplane.UpdateNodeGraphRequest.edges:type_name -> controlplane.Edge
	15, // 8: controlplane.GetNodeGraphStatusResponse.node_statuses:type_name -> controlplane.GetNodeGraphStatusResponse.NodeStatusesEntry
	16, // 9: controlplane.NodeGraphResponse.status:type_name -> common.StatusCode
	0,  // 10: controlplane.NodeGraphResponse.graph:type_name -> controlplane.NodeGraph
	17, // 11: controlplane.NodeGraphResponse.errors:type_name -> common.ValidationError
	5,  // 12: controlplane.NodeService.CreateNodeGraph:input_type -> controlplane.CreateNodeGraphRequest
	6,  // 13: controlplane.NodeService.GetNodeGraph:input_type -> controlplane.GetNodeGraphRequest
	7,  // 14: controlplane.NodeService.UpdateNodeGraph:input_type -> controlplane.UpdateNodeGraphRequest
	8,  // 15: controlplane.NodeService.DeleteNodeGraph:input_type -> controlplane.DeleteNodeGraphRequest
	9,  // 16: controlplane.NodeService.DeployNodeGraph:input_type -> controlplane.DeployNodeGraphRequest
	10, // 17: controlplane.NodeService.GetNodeGraphStatus:input_type -> controlplane.GetNodeGraphStatusRequest
	12, // 18: controlplane.NodeService.GetDeploymentLogs:input_type -> controlplane.GetDeploymentLogsRequest
	14, // 19: controlplane.NodeService.CreateNodeGraph:output_type -> controlplane.NodeGraphResponse
	14, // 20: controlplane.NodeService.GetNodeGraph:output_type -> controlplane.NodeGraphResponse
	14, // 21: controlplane.NodeService.UpdateNodeGraph:output_type -> controlplane.NodeGraphResponse
	18, // 22: controlplane.NodeService.DeleteNodeGraph:output_type -> common.MessageResponse
	18, // 23: controlplane.NodeService.DeployNodeGraph:output_type -> common.MessageResponse
	11, // 24: controlplane.NodeService.GetNodeGraphStatus:output_type -> controlplane.GetNodeGraphStatusResponse
	13, // 25: controlplane.NodeService.GetDeploymentLogs:output_type -> controlplane.GetDeploymentLogsResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_controlplane_node_proto_init() }
func file_controlplane_node_proto_init() {
	if File_controlplane_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_node_proto_rawDesc), len(file_controlplane_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_node_proto_goTypes,
		DependencyIndexes: file_controlplane_node_proto_depIdxs,
		MessageInfos:      file_controlplane_node_proto_msgTypes,
	}.Build()
	File_controlplane_node_proto = out.File
	file_controlplane_node_proto_goTypes = nil
	file_controlplane_node_proto_depIdxs = nil
}
