// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: controlplane/services.proto

package controlplane

import (
	common "github.com/zhinea/sylix/internal/infra/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceType int32

const (
	ServiceType_CLUSTER ServiceType = 0
	ServiceType_NODE    ServiceType = 1
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "CLUSTER",
		1: "NODE",
	}
	ServiceType_value = map[string]int32{
		"CLUSTER": 0,
		"NODE":    1,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_services_proto_enumTypes[0].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_controlplane_services_proto_enumTypes[0]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_services_proto_rawDescGZIP(), []int{0}
}

type ServiceStatus int32

const (
	ServiceStatus_OFFLINE      ServiceStatus = 0
	ServiceStatus_PROVISIONING ServiceStatus = 1
	ServiceStatus_RUNNING      ServiceStatus = 2
	ServiceStatus_DELETING     ServiceStatus = 3
	ServiceStatus_ERROR        ServiceStatus = 4
)

// Enum value maps for ServiceStatus.
var (
	ServiceStatus_name = map[int32]string{
		0: "OFFLINE",
		1: "PROVISIONING",
		2: "RUNNING",
		3: "DELETING",
		4: "ERROR",
	}
	ServiceStatus_value = map[string]int32{
		"OFFLINE":      0,
		"PROVISIONING": 1,
		"RUNNING":      2,
		"DELETING":     3,
		"ERROR":        4,
	}
)

func (x ServiceStatus) Enum() *ServiceStatus {
	p := new(ServiceStatus)
	*p = x
	return p
}

func (x ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_services_proto_enumTypes[1].Descriptor()
}

func (ServiceStatus) Type() protoreflect.EnumType {
	return &file_controlplane_services_proto_enumTypes[1]
}

func (x ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStatus.Descriptor instead.
func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_services_proto_rawDescGZIP(), []int{1}
}

type ServicePortType int32

const (
	ServicePortType_IN  ServicePortType = 0
	ServicePortType_OUT ServicePortType = 1
)

// Enum value maps for ServicePortType.
var (
	ServicePortType_name = map[int32]string{
		0: "IN",
		1: "OUT",
	}
	ServicePortType_value = map[string]int32{
		"IN":  0,
		"OUT": 1,
	}
)

func (x ServicePortType) Enum() *ServicePortType {
	p := new(ServicePortType)
	*p = x
	return p
}

func (x ServicePortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServicePortType) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_services_proto_enumTypes[2].Descriptor()
}

func (ServicePortType) Type() protoreflect.EnumType {
	return &file_controlplane_services_proto_enumTypes[2]
}

func (x ServicePortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServicePortType.Descriptor instead.
func (ServicePortType) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_services_proto_rawDescGZIP(), []int{2}
}

type TakeAction int32

const (
	TakeAction_START   TakeAction = 0
	TakeAction_STOP    TakeAction = 1
	TakeAction_RESTART TakeAction = 2
)

// Enum value maps for TakeAction.
var (
	TakeAction_name = map[int32]string{
		0: "START",
		1: "STOP",
		2: "RESTART",
	}
	TakeAction_value = map[string]int32{
		"START":   0,
		"STOP":    1,
		"RESTART": 2,
	}
)

func (x TakeAction) Enum() *TakeAction {
	p := new(TakeAction)
	*p = x
	return p
}

func (x TakeAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TakeAction) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_services_proto_enumTypes[3].Descriptor()
}

func (TakeAction) Type() protoreflect.EnumType {
	return &file_controlplane_services_proto_enumTypes[3]
}

func (x TakeAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TakeAction.Descriptor instead.
func (TakeAction) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_services_proto_rawDescGZIP(), []int{3}
}

// Query
type QueryId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryId) Reset() {
	*x = QueryId{}
	mi := &file_controlplane_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryId) ProtoMessage() {}

func (x *QueryId) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryId.ProtoReflect.Descriptor instead.
func (*QueryId) Descriptor() ([]byte, []int) {
	return file_controlplane_services_proto_rawDescGZIP(), []int{0}
}

func (x *QueryId) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type QueryServices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Order         string                 `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryServices) Reset() {
	*x = QueryServices{}
	mi := &file_controlplane_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryServices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryServices) ProtoMessage() {}

func (x *QueryServices) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryServices.ProtoReflect.Descriptor instead.
func (*QueryServices) Descriptor() ([]byte, []int) {
	return file_controlplane_services_proto_rawDescGZIP(), []int{1}
}

func (x *QueryServices) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryServices) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryServices) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *QueryServices) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *QueryServices) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type QueryTakeActions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        TakeAction             `protobuf:"varint,1,opt,name=action,proto3,enum=controlplane.TakeAction" json:"action,omitempty"`
	ServiceIds    []string               `protobuf:"bytes,2,rep,name=service_ids,json=serviceIds,proto3" json:"service_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTakeActions) Reset() {
	*x = QueryTakeActions{}
	mi := &file_controlplane_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTakeActions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTakeActions) ProtoMessage() {}

func (x *QueryTakeActions) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTakeActions.ProtoReflect.Descriptor instead.
func (*QueryTakeActions) Descriptor() ([]byte, []int) {
	return file_controlplane_services_proto_rawDescGZIP(), []int{2}
}

func (x *QueryTakeActions) GetAction() TakeAction {
	if x != nil {
		return x.Action
	}
	return TakeAction_START
}

func (x *QueryTakeActions) GetServiceIds() []string {
	if x != nil {
		return x.ServiceIds
	}
	return nil
}

type QueryLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // default is 100 lines
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`   // reversed page. if 1 this mean is the latest logs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLog) Reset() {
	*x = QueryLog{}
	mi := &file_controlplane_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLog) ProtoMessage() {}

func (x *QueryLog) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLog.ProtoReflect.Descriptor instead.
func (*QueryLog) Descriptor() ([]byte, []int) {
	return file_controlplane_services_proto_rawDescGZIP(), []int{3}
}

func (x *QueryLog) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *QueryLog) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryLog) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// Utils
type ServiceNodeField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // text, number, boolean, options, etc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceNodeField) Reset() {
	*x = ServiceNodeField{}
	mi := &file_controlplane_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceNodeField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceNodeField) ProtoMessage() {}

func (x *ServiceNodeField) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceNodeField.ProtoReflect.Descriptor instead.
func (*ServiceNodeField) Descriptor() ([]byte, []int) {
	return file_controlplane_services_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceNodeField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ServiceNodeField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ServiceNodeField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ServicePort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ServicePortType        `protobuf:"varint,1,opt,name=type,proto3,enum=controlplane.ServicePortType" json:"type,omitempty"` // IN or OUT
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // tcp, udp, etc
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	EnabledExpose bool                   `protobuf:"varint,5,opt,name=enabled_expose,json=enabledExpose,proto3" json:"enabled_expose,omitempty"` // this mean, if true, expose to internet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePort) Reset() {
	*x = ServicePort{}
	mi := &file_controlplane_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePort) ProtoMessage() {}

func (x *ServicePort) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePort.ProtoReflect.Descriptor instead.
func (*ServicePort) Descriptor() ([]byte, []int) {
	return file_controlplane_services_proto_rawDescGZIP(), []int{5}
}

func (x *ServicePort) GetType() ServicePortType {
	if x != nil {
		return x.Type
	}
	return ServicePortType_IN
}

func (x *ServicePort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServicePort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ServicePort) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServicePort) GetEnabledExpose() bool {
	if x != nil {
		return x.EnabledExpose
	}
	return false
}

type ServiceContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // docker container id
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"` // image container used.
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceContainer) Reset() {
	*x = ServiceContainer{}
	mi := &file_controlplane_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceContainer) ProtoMessage() {}

func (x *ServiceContainer) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceContainer.ProtoReflect.Descriptor instead.
func (*ServiceContainer) Descriptor() ([]byte, []int) {
	return file_controlplane_services_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceContainer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceContainer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceContainer) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ServiceContainer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ServiceContainer) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ServiceApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`         // e.g. supabase, neondb, etc
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // base version
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"` // e.g. if neondb -> pageserver, safekeeper, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceApp) Reset() {
	*x = ServiceApp{}
	mi := &file_controlplane_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceApp) ProtoMessage() {}

func (x *ServiceApp) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceApp.ProtoReflect.Descriptor instead.
func (*ServiceApp) Descriptor() ([]byte, []int) {
	return file_controlplane_services_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceApp) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ServiceApp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceApp) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// Base
type CreateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          ServiceType            `protobuf:"varint,2,opt,name=type,proto3,enum=controlplane.ServiceType" json:"type,omitempty"`
	App           *ServiceApp            `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	Fields        []*ServiceNodeField    `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	ServerId      string                 `protobuf:"bytes,5,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ParentId      *string                `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceRequest) Reset() {
	*x = CreateServiceRequest{}
	mi := &file_controlplane_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequest) ProtoMessage() {}

func (x *CreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_services_proto_rawDescGZIP(), []int{8}
}

func (x *CreateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServiceRequest) GetType() ServiceType {
	if x != nil {
		return x.Type
	}
	return ServiceType_CLUSTER
}

func (x *CreateServiceRequest) GetApp() *ServiceApp {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *CreateServiceRequest) GetFields() []*ServiceNodeField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *CreateServiceRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateServiceRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

// always get latest the logs
type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []string               `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Status        ServiceStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=controlplane.ServiceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_controlplane_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_services_proto_rawDescGZIP(), []int{9}
}

func (x *LogsResponse) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *LogsResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *LogsResponse) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_OFFLINE
}

type ServiceNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// app of the service, like if supabase, app is supabase. or if neondb, app is neondb
	App *ServiceApp `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	// type service, cluster or node
	Type ServiceType `protobuf:"varint,4,opt,name=type,proto3,enum=controlplane.ServiceType" json:"type,omitempty"`
	// status of the service
	Status ServiceStatus `protobuf:"varint,5,opt,name=status,proto3,enum=controlplane.ServiceStatus" json:"status,omitempty"`
	// fields of the service
	Fields []*ServiceNodeField `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	// server id of the service
	ServerId string `protobuf:"bytes,7,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// nodes. like if app = neondb, so the service children is safekeeper, pageserver, etc
	Nodes []*ServiceNode `protobuf:"bytes,8,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// ports of the service, like if app = neondb, ports is 5432, 5433, etc
	Ports []*ServicePort `protobuf:"bytes,9,rep,name=ports,proto3" json:"ports,omitempty"`
	// image container of docker
	Container *ServiceContainer `protobuf:"bytes,10,opt,name=container,proto3" json:"container,omitempty"`
	// parent id of the service. default is null
	ParentId string `protobuf:"bytes,11,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// timestamp at of the service
	CreatedAt     string `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceNode) Reset() {
	*x = ServiceNode{}
	mi := &file_controlplane_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceNode) ProtoMessage() {}

func (x *ServiceNode) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceNode.ProtoReflect.Descriptor instead.
func (*ServiceNode) Descriptor() ([]byte, []int) {
	return file_controlplane_services_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceNode) GetApp() *ServiceApp {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *ServiceNode) GetType() ServiceType {
	if x != nil {
		return x.Type
	}
	return ServiceType_CLUSTER
}

func (x *ServiceNode) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_OFFLINE
}

func (x *ServiceNode) GetFields() []*ServiceNodeField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ServiceNode) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServiceNode) GetNodes() []*ServiceNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ServiceNode) GetPorts() []*ServicePort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ServiceNode) GetContainer() *ServiceContainer {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *ServiceNode) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ServiceNode) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ServiceNode) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ServiceNodesResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        common.StatusCode         `protobuf:"varint,1,opt,name=status,proto3,enum=common.StatusCode" json:"status,omitempty"`
	Services      []*ServiceNode            `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	Errors        []*common.ValidationError `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Error         *string                   `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceNodesResponse) Reset() {
	*x = ServiceNodesResponse{}
	mi := &file_controlplane_services_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceNodesResponse) ProtoMessage() {}

func (x *ServiceNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_services_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceNodesResponse.ProtoReflect.Descriptor instead.
func (*ServiceNodesResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_services_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceNodesResponse) GetStatus() common.StatusCode {
	if x != nil {
		return x.Status
	}
	return common.StatusCode(0)
}

func (x *ServiceNodesResponse) GetServices() []*ServiceNode {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ServiceNodesResponse) GetErrors() []*common.ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ServiceNodesResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_controlplane_services_proto protoreflect.FileDescriptor

const file_controlplane_services_proto_rawDesc = "" +
	"\n" +
	"\x1bcontrolplane/services.proto\x12\fcontrolplane\x1a\x17common/validation.proto\x1a\x13common/common.proto\"(\n" +
	"\aQueryId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"{\n" +
	"\rQueryServices\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12\x14\n" +
	"\x05order\x18\x05 \x01(\tR\x05order\"e\n" +
	"\x10QueryTakeActions\x120\n" +
	"\x06action\x18\x01 \x01(\x0e2\x18.controlplane.TakeActionR\x06action\x12\x1f\n" +
	"\vservice_ids\x18\x02 \x03(\tR\n" +
	"serviceIds\"S\n" +
	"\bQueryLog\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"N\n" +
	"\x10ServiceNodeField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xab\x01\n" +
	"\vServicePort\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.controlplane.ServicePortTypeR\x04type\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12%\n" +
	"\x0eenabled_expose\x18\x05 \x01(\bR\renabledExpose\"\x8a\x01\n" +
	"\x10ServiceContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"R\n" +
	"\n" +
	"ServiceApp\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\"\x8a\x02\n" +
	"\x14CreateServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.controlplane.ServiceTypeR\x04type\x12*\n" +
	"\x03app\x18\x03 \x01(\v2\x18.controlplane.ServiceAppR\x03app\x126\n" +
	"\x06fields\x18\x04 \x03(\v2\x1e.controlplane.ServiceNodeFieldR\x06fields\x12\x1b\n" +
	"\tserver_id\x18\x05 \x01(\tR\bserverId\x12 \n" +
	"\tparent_id\x18\x06 \x01(\tH\x00R\bparentId\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_id\"v\n" +
	"\fLogsResponse\x12\x12\n" +
	"\x04logs\x18\x01 \x03(\tR\x04logs\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.controlplane.ServiceStatusR\x06status\"\x91\x04\n" +
	"\vServiceNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x03app\x18\x03 \x01(\v2\x18.controlplane.ServiceAppR\x03app\x12-\n" +
	"\x04type\x18\x04 \x01(\x0e2\x19.controlplane.ServiceTypeR\x04type\x123\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1b.controlplane.ServiceStatusR\x06status\x126\n" +
	"\x06fields\x18\x06 \x03(\v2\x1e.controlplane.ServiceNodeFieldR\x06fields\x12\x1b\n" +
	"\tserver_id\x18\a \x01(\tR\bserverId\x12/\n" +
	"\x05nodes\x18\b \x03(\v2\x19.controlplane.ServiceNodeR\x05nodes\x12/\n" +
	"\x05ports\x18\t \x03(\v2\x19.controlplane.ServicePortR\x05ports\x12<\n" +
	"\tcontainer\x18\n" +
	" \x01(\v2\x1e.controlplane.ServiceContainerR\tcontainer\x12\x1b\n" +
	"\tparent_id\x18\v \x01(\tR\bparentId\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\"\xcf\x01\n" +
	"\x14ServiceNodesResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.common.StatusCodeR\x06status\x125\n" +
	"\bservices\x18\x02 \x03(\v2\x19.controlplane.ServiceNodeR\bservices\x12/\n" +
	"\x06errors\x18\x03 \x03(\v2\x17.common.ValidationErrorR\x06errors\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error*$\n" +
	"\vServiceType\x12\v\n" +
	"\aCLUSTER\x10\x00\x12\b\n" +
	"\x04NODE\x10\x01*T\n" +
	"\rServiceStatus\x12\v\n" +
	"\aOFFLINE\x10\x00\x12\x10\n" +
	"\fPROVISIONING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\f\n" +
	"\bDELETING\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04*\"\n" +
	"\x0fServicePortType\x12\x06\n" +
	"\x02IN\x10\x00\x12\a\n" +
	"\x03OUT\x10\x01*.\n" +
	"\n" +
	"TakeAction\x12\t\n" +
	"\x05START\x10\x00\x12\b\n" +
	"\x04STOP\x10\x01\x12\v\n" +
	"\aRESTART\x10\x022\xf0\x03\n" +
	"\x0fServicesService\x12F\n" +
	"\x03All\x12\x1b.controlplane.QueryServices\x1a\".controlplane.ServiceNodesResponse\x127\n" +
	"\x03One\x12\x15.controlplane.QueryId\x1a\x19.controlplane.ServiceNode\x12G\n" +
	"\x06Create\x12\".controlplane.CreateServiceRequest\x1a\x19.controlplane.ServiceNode\x12G\n" +
	"\x06Update\x12\".controlplane.CreateServiceRequest\x1a\x19.controlplane.ServiceNode\x128\n" +
	"\x06Delete\x12\x15.controlplane.QueryId\x1a\x17.common.MessageResponse\x12Q\n" +
	"\vTakeActions\x12\x1e.controlplane.QueryTakeActions\x1a\".controlplane.ServiceNodesResponse\x12=\n" +
	"\aGetLogs\x12\x16.controlplane.QueryLog\x1a\x1a.controlplane.LogsResponseB;Z9github.com/zhinea/sylix/internal/infra/proto/controlplaneb\x06proto3"

var (
	file_controlplane_services_proto_rawDescOnce sync.Once
	file_controlplane_services_proto_rawDescData []byte
)

func file_controlplane_services_proto_rawDescGZIP() []byte {
	file_controlplane_services_proto_rawDescOnce.Do(func() {
		file_controlplane_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_services_proto_rawDesc), len(file_controlplane_services_proto_rawDesc)))
	})
	return file_controlplane_services_proto_rawDescData
}

var file_controlplane_services_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_controlplane_services_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_controlplane_services_proto_goTypes = []any{
	(ServiceType)(0),               // 0: controlplane.ServiceType
	(ServiceStatus)(0),             // 1: controlplane.ServiceStatus
	(ServicePortType)(0),           // 2: controlplane.ServicePortType
	(TakeAction)(0),                // 3: controlplane.TakeAction
	(*QueryId)(nil),                // 4: controlplane.QueryId
	(*QueryServices)(nil),          // 5: controlplane.QueryServices
	(*QueryTakeActions)(nil),       // 6: controlplane.QueryTakeActions
	(*QueryLog)(nil),               // 7: controlplane.QueryLog
	(*ServiceNodeField)(nil),       // 8: controlplane.ServiceNodeField
	(*ServicePort)(nil),            // 9: controlplane.ServicePort
	(*ServiceContainer)(nil),       // 10: controlplane.ServiceContainer
	(*ServiceApp)(nil),             // 11: controlplane.ServiceApp
	(*CreateServiceRequest)(nil),   // 12: controlplane.CreateServiceRequest
	(*LogsResponse)(nil),           // 13: controlplane.LogsResponse
	(*ServiceNode)(nil),            // 14: controlplane.ServiceNode
	(*ServiceNodesResponse)(nil),   // 15: controlplane.ServiceNodesResponse
	(common.StatusCode)(0),         // 16: common.StatusCode
	(*common.ValidationError)(nil), // 17: common.ValidationError
	(*common.MessageResponse)(nil), // 18: common.MessageResponse
}
var file_controlplane_services_proto_depIdxs = []int32{
	3,  // 0: controlplane.QueryTakeActions.action:type_name -> controlplane.TakeAction
	2,  // 1: controlplane.ServicePort.type:type_name -> controlplane.ServicePortType
	0,  // 2: controlplane.CreateServiceRequest.type:type_name -> controlplane.ServiceType
	11, // 3: controlplane.CreateServiceRequest.app:type_name -> controlplane.ServiceApp
	8,  // 4: controlplane.CreateServiceRequest.fields:type_name -> controlplane.ServiceNodeField
	1,  // 5: controlplane.LogsResponse.status:type_name -> controlplane.ServiceStatus
	11, // 6: controlplane.ServiceNode.app:type_name -> controlplane.ServiceApp
	0,  // 7: controlplane.ServiceNode.type:type_name -> controlplane.ServiceType
	1,  // 8: controlplane.ServiceNode.status:type_name -> controlplane.ServiceStatus
	8,  // 9: controlplane.ServiceNode.fields:type_name -> controlplane.ServiceNodeField
	14, // 10: controlplane.ServiceNode.nodes:type_name -> controlplane.ServiceNode
	9,  // 11: controlplane.ServiceNode.ports:type_name -> controlplane.ServicePort
	10, // 12: controlplane.ServiceNode.container:type_name -> controlplane.ServiceContainer
	16, // 13: controlplane.ServiceNodesResponse.status:type_name -> common.StatusCode
	14, // 14: controlplane.ServiceNodesResponse.services:type_name -> controlplane.ServiceNode
	17, // 15: controlplane.ServiceNodesResponse.errors:type_name -> common.ValidationError
	5,  // 16: controlplane.ServicesService.All:input_type -> controlplane.QueryServices
	4,  // 17: controlplane.ServicesService.One:input_type -> controlplane.QueryId
	12, // 18: controlplane.ServicesService.Create:input_type -> controlplane.CreateServiceRequest
	12, // 19: controlplane.ServicesService.Update:input_type -> controlplane.CreateServiceRequest
	4,  // 20: controlplane.ServicesService.Delete:input_type -> controlplane.QueryId
	6,  // 21: controlplane.ServicesService.TakeActions:input_type -> controlplane.QueryTakeActions
	7,  // 22: controlplane.ServicesService.GetLogs:input_type -> controlplane.QueryLog
	15, // 23: controlplane.ServicesService.All:output_type -> controlplane.ServiceNodesResponse
	14, // 24: controlplane.ServicesService.One:output_type -> controlplane.ServiceNode
	14, // 25: controlplane.ServicesService.Create:output_type -> controlplane.ServiceNode
	14, // 26: controlplane.ServicesService.Update:output_type -> controlplane.ServiceNode
	18, // 27: controlplane.ServicesService.Delete:output_type -> common.MessageResponse
	15, // 28: controlplane.ServicesService.TakeActions:output_type -> controlplane.ServiceNodesResponse
	13, // 29: controlplane.ServicesService.GetLogs:output_type -> controlplane.LogsResponse
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_controlplane_services_proto_init() }
func file_controlplane_services_proto_init() {
	if File_controlplane_services_proto != nil {
		return
	}
	file_controlplane_services_proto_msgTypes[8].OneofWrappers = []any{}
	file_controlplane_services_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_services_proto_rawDesc), len(file_controlplane_services_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_services_proto_goTypes,
		DependencyIndexes: file_controlplane_services_proto_depIdxs,
		EnumInfos:         file_controlplane_services_proto_enumTypes,
		MessageInfos:      file_controlplane_services_proto_msgTypes,
	}.Build()
	File_controlplane_services_proto = out.File
	file_controlplane_services_proto_goTypes = nil
	file_controlplane_services_proto_depIdxs = nil
}
