// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.12.4
// source: controlplane/server.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Empty } from "../common/common";
import { ValidationError } from "../common/validation";

export const protobufPackage = "controlplane";

export enum StatusCode {
  UNSPECIFIED = 0,
  OK = 200,
  CREATED = 201,
  NOT_FOUND = 404,
  INTERNAL_ERROR = 500,
  BAD_REQUEST = 400,
  VALIDATION_FAILED = 402,
  UNRECOGNIZED = -1,
}

export function statusCodeFromJSON(object: any): StatusCode {
  switch (object) {
    case 0:
    case "UNSPECIFIED":
      return StatusCode.UNSPECIFIED;
    case 200:
    case "OK":
      return StatusCode.OK;
    case 201:
    case "CREATED":
      return StatusCode.CREATED;
    case 404:
    case "NOT_FOUND":
      return StatusCode.NOT_FOUND;
    case 500:
    case "INTERNAL_ERROR":
      return StatusCode.INTERNAL_ERROR;
    case 400:
    case "BAD_REQUEST":
      return StatusCode.BAD_REQUEST;
    case 402:
    case "VALIDATION_FAILED":
      return StatusCode.VALIDATION_FAILED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return StatusCode.UNRECOGNIZED;
  }
}

export function statusCodeToJSON(object: StatusCode): string {
  switch (object) {
    case StatusCode.UNSPECIFIED:
      return "UNSPECIFIED";
    case StatusCode.OK:
      return "OK";
    case StatusCode.CREATED:
      return "CREATED";
    case StatusCode.NOT_FOUND:
      return "NOT_FOUND";
    case StatusCode.INTERNAL_ERROR:
      return "INTERNAL_ERROR";
    case StatusCode.BAD_REQUEST:
      return "BAD_REQUEST";
    case StatusCode.VALIDATION_FAILED:
      return "VALIDATION_FAILED";
    case StatusCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Status dimana hanya untuk koneksi ke server, apakah koneksi berhasil atau tidak */
export enum StatusServer {
  STATUS_SERVER_UNSPECIFIED = 0,
  CONNECTED = 1,
  DISCONNECTED = 2,
  UNRECOGNIZED = -1,
}

export function statusServerFromJSON(object: any): StatusServer {
  switch (object) {
    case 0:
    case "STATUS_SERVER_UNSPECIFIED":
      return StatusServer.STATUS_SERVER_UNSPECIFIED;
    case 1:
    case "CONNECTED":
      return StatusServer.CONNECTED;
    case 2:
    case "DISCONNECTED":
      return StatusServer.DISCONNECTED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return StatusServer.UNRECOGNIZED;
  }
}

export function statusServerToJSON(object: StatusServer): string {
  switch (object) {
    case StatusServer.STATUS_SERVER_UNSPECIFIED:
      return "STATUS_SERVER_UNSPECIFIED";
    case StatusServer.CONNECTED:
      return "CONNECTED";
    case StatusServer.DISCONNECTED:
      return "DISCONNECTED";
    case StatusServer.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum AgentStatusServer {
  AGENT_STATUS_SERVER_UNSPECIFIED = 0,
  INSTALLING = 1,
  CONFIGURING = 2,
  FINALIZING_SETUP = 3,
  SUCCESS = 4,
  FAILED = 5,
  UNRECOGNIZED = -1,
}

export function agentStatusServerFromJSON(object: any): AgentStatusServer {
  switch (object) {
    case 0:
    case "AGENT_STATUS_SERVER_UNSPECIFIED":
      return AgentStatusServer.AGENT_STATUS_SERVER_UNSPECIFIED;
    case 1:
    case "INSTALLING":
      return AgentStatusServer.INSTALLING;
    case 2:
    case "CONFIGURING":
      return AgentStatusServer.CONFIGURING;
    case 3:
    case "FINALIZING_SETUP":
      return AgentStatusServer.FINALIZING_SETUP;
    case 4:
    case "SUCCESS":
      return AgentStatusServer.SUCCESS;
    case 5:
    case "FAILED":
      return AgentStatusServer.FAILED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AgentStatusServer.UNRECOGNIZED;
  }
}

export function agentStatusServerToJSON(object: AgentStatusServer): string {
  switch (object) {
    case AgentStatusServer.AGENT_STATUS_SERVER_UNSPECIFIED:
      return "AGENT_STATUS_SERVER_UNSPECIFIED";
    case AgentStatusServer.INSTALLING:
      return "INSTALLING";
    case AgentStatusServer.CONFIGURING:
      return "CONFIGURING";
    case AgentStatusServer.FINALIZING_SETUP:
      return "FINALIZING_SETUP";
    case AgentStatusServer.SUCCESS:
      return "SUCCESS";
    case AgentStatusServer.FAILED:
      return "FAILED";
    case AgentStatusServer.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface GetRealtimeStatsRequest {
  serverId: string;
  limit: number;
}

export interface ServerPing {
  id: string;
  serverId: string;
  responseTime: number;
  status: string;
  error: string;
  createdAt: string;
}

export interface GetRealtimeStatsResponse {
  pings: ServerPing[];
}

export interface ConfigureAgentRequest {
  serverId: string;
  config: string;
}

export interface UpdateAgentPortRequest {
  serverId: string;
  port: number;
}

export interface UpdateServerTimeZoneRequest {
  serverId: string;
  timezone: string;
}

export interface GetStatsRequest {
  serverId: string;
}

export interface ServerStat {
  id: string;
  serverId: string;
  averageResponseTime: number;
  minResponseTime: number;
  maxResponseTime: number;
  pingCount: number;
  successRate: number;
  timestamp: string;
}

export interface GetStatsResponse {
  stats: ServerStat[];
}

export interface GetAccidentsRequest {
  serverId: string;
  startDate: string;
  endDate: string;
  resolved: boolean;
  page: number;
  pageSize: number;
}

export interface ServerAccident {
  id: string;
  serverId: string;
  responseTime: number;
  error: string;
  details: string;
  resolved: boolean;
  createdAt: string;
}

export interface GetAccidentsResponse {
  accidents: ServerAccident[];
  totalCount: number;
}

export interface Id {
  id: string;
}

export interface ServerResponse {
  status: StatusCode;
  server: Server | undefined;
  errors: ValidationError[];
  error?: string | undefined;
}

export interface ServersResponse {
  status: StatusCode;
  servers: Server[];
  errors: ValidationError[];
  error?: string | undefined;
}

export interface Server {
  id: string;
  name: string;
  ipAddress: string;
  port: number;
  protocol: string;
  credential: ServerCredential | undefined;
  isRoot: number;
  status: StatusServer;
  agentStatus: AgentStatusServer;
  agentLogs: string;
}

export interface ServerCredential {
  username: string;
  password?: string | undefined;
  sshKey?: string | undefined;
}

export interface MessageResponse {
  status: StatusCode;
  message: string;
}

function createBaseGetRealtimeStatsRequest(): GetRealtimeStatsRequest {
  return { serverId: "", limit: 0 };
}

export const GetRealtimeStatsRequest: MessageFns<GetRealtimeStatsRequest> = {
  encode(message: GetRealtimeStatsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverId !== "") {
      writer.uint32(10).string(message.serverId);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetRealtimeStatsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetRealtimeStatsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetRealtimeStatsRequest {
    return {
      serverId: isSet(object.serverId) ? globalThis.String(object.serverId) : "",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: GetRealtimeStatsRequest): unknown {
    const obj: any = {};
    if (message.serverId !== "") {
      obj.serverId = message.serverId;
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetRealtimeStatsRequest>, I>>(base?: I): GetRealtimeStatsRequest {
    return GetRealtimeStatsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetRealtimeStatsRequest>, I>>(object: I): GetRealtimeStatsRequest {
    const message = createBaseGetRealtimeStatsRequest();
    message.serverId = object.serverId ?? "";
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseServerPing(): ServerPing {
  return { id: "", serverId: "", responseTime: 0, status: "", error: "", createdAt: "" };
}

export const ServerPing: MessageFns<ServerPing> = {
  encode(message: ServerPing, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.serverId !== "") {
      writer.uint32(18).string(message.serverId);
    }
    if (message.responseTime !== 0) {
      writer.uint32(24).int64(message.responseTime);
    }
    if (message.status !== "") {
      writer.uint32(34).string(message.status);
    }
    if (message.error !== "") {
      writer.uint32(42).string(message.error);
    }
    if (message.createdAt !== "") {
      writer.uint32(50).string(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerPing {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerPing();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serverId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.responseTime = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerPing {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      serverId: isSet(object.serverId) ? globalThis.String(object.serverId) : "",
      responseTime: isSet(object.responseTime) ? globalThis.Number(object.responseTime) : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      error: isSet(object.error) ? globalThis.String(object.error) : "",
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
    };
  },

  toJSON(message: ServerPing): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.serverId !== "") {
      obj.serverId = message.serverId;
    }
    if (message.responseTime !== 0) {
      obj.responseTime = Math.round(message.responseTime);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerPing>, I>>(base?: I): ServerPing {
    return ServerPing.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerPing>, I>>(object: I): ServerPing {
    const message = createBaseServerPing();
    message.id = object.id ?? "";
    message.serverId = object.serverId ?? "";
    message.responseTime = object.responseTime ?? 0;
    message.status = object.status ?? "";
    message.error = object.error ?? "";
    message.createdAt = object.createdAt ?? "";
    return message;
  },
};

function createBaseGetRealtimeStatsResponse(): GetRealtimeStatsResponse {
  return { pings: [] };
}

export const GetRealtimeStatsResponse: MessageFns<GetRealtimeStatsResponse> = {
  encode(message: GetRealtimeStatsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.pings) {
      ServerPing.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetRealtimeStatsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetRealtimeStatsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pings.push(ServerPing.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetRealtimeStatsResponse {
    return {
      pings: globalThis.Array.isArray(object?.pings) ? object.pings.map((e: any) => ServerPing.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetRealtimeStatsResponse): unknown {
    const obj: any = {};
    if (message.pings?.length) {
      obj.pings = message.pings.map((e) => ServerPing.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetRealtimeStatsResponse>, I>>(base?: I): GetRealtimeStatsResponse {
    return GetRealtimeStatsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetRealtimeStatsResponse>, I>>(object: I): GetRealtimeStatsResponse {
    const message = createBaseGetRealtimeStatsResponse();
    message.pings = object.pings?.map((e) => ServerPing.fromPartial(e)) || [];
    return message;
  },
};

function createBaseConfigureAgentRequest(): ConfigureAgentRequest {
  return { serverId: "", config: "" };
}

export const ConfigureAgentRequest: MessageFns<ConfigureAgentRequest> = {
  encode(message: ConfigureAgentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverId !== "") {
      writer.uint32(10).string(message.serverId);
    }
    if (message.config !== "") {
      writer.uint32(18).string(message.config);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConfigureAgentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfigureAgentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.config = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConfigureAgentRequest {
    return {
      serverId: isSet(object.serverId) ? globalThis.String(object.serverId) : "",
      config: isSet(object.config) ? globalThis.String(object.config) : "",
    };
  },

  toJSON(message: ConfigureAgentRequest): unknown {
    const obj: any = {};
    if (message.serverId !== "") {
      obj.serverId = message.serverId;
    }
    if (message.config !== "") {
      obj.config = message.config;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConfigureAgentRequest>, I>>(base?: I): ConfigureAgentRequest {
    return ConfigureAgentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConfigureAgentRequest>, I>>(object: I): ConfigureAgentRequest {
    const message = createBaseConfigureAgentRequest();
    message.serverId = object.serverId ?? "";
    message.config = object.config ?? "";
    return message;
  },
};

function createBaseUpdateAgentPortRequest(): UpdateAgentPortRequest {
  return { serverId: "", port: 0 };
}

export const UpdateAgentPortRequest: MessageFns<UpdateAgentPortRequest> = {
  encode(message: UpdateAgentPortRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverId !== "") {
      writer.uint32(10).string(message.serverId);
    }
    if (message.port !== 0) {
      writer.uint32(16).int32(message.port);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateAgentPortRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateAgentPortRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.port = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateAgentPortRequest {
    return {
      serverId: isSet(object.serverId) ? globalThis.String(object.serverId) : "",
      port: isSet(object.port) ? globalThis.Number(object.port) : 0,
    };
  },

  toJSON(message: UpdateAgentPortRequest): unknown {
    const obj: any = {};
    if (message.serverId !== "") {
      obj.serverId = message.serverId;
    }
    if (message.port !== 0) {
      obj.port = Math.round(message.port);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateAgentPortRequest>, I>>(base?: I): UpdateAgentPortRequest {
    return UpdateAgentPortRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateAgentPortRequest>, I>>(object: I): UpdateAgentPortRequest {
    const message = createBaseUpdateAgentPortRequest();
    message.serverId = object.serverId ?? "";
    message.port = object.port ?? 0;
    return message;
  },
};

function createBaseUpdateServerTimeZoneRequest(): UpdateServerTimeZoneRequest {
  return { serverId: "", timezone: "" };
}

export const UpdateServerTimeZoneRequest: MessageFns<UpdateServerTimeZoneRequest> = {
  encode(message: UpdateServerTimeZoneRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverId !== "") {
      writer.uint32(10).string(message.serverId);
    }
    if (message.timezone !== "") {
      writer.uint32(18).string(message.timezone);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateServerTimeZoneRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateServerTimeZoneRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.timezone = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateServerTimeZoneRequest {
    return {
      serverId: isSet(object.serverId) ? globalThis.String(object.serverId) : "",
      timezone: isSet(object.timezone) ? globalThis.String(object.timezone) : "",
    };
  },

  toJSON(message: UpdateServerTimeZoneRequest): unknown {
    const obj: any = {};
    if (message.serverId !== "") {
      obj.serverId = message.serverId;
    }
    if (message.timezone !== "") {
      obj.timezone = message.timezone;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateServerTimeZoneRequest>, I>>(base?: I): UpdateServerTimeZoneRequest {
    return UpdateServerTimeZoneRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateServerTimeZoneRequest>, I>>(object: I): UpdateServerTimeZoneRequest {
    const message = createBaseUpdateServerTimeZoneRequest();
    message.serverId = object.serverId ?? "";
    message.timezone = object.timezone ?? "";
    return message;
  },
};

function createBaseGetStatsRequest(): GetStatsRequest {
  return { serverId: "" };
}

export const GetStatsRequest: MessageFns<GetStatsRequest> = {
  encode(message: GetStatsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverId !== "") {
      writer.uint32(10).string(message.serverId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStatsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStatsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetStatsRequest {
    return { serverId: isSet(object.serverId) ? globalThis.String(object.serverId) : "" };
  },

  toJSON(message: GetStatsRequest): unknown {
    const obj: any = {};
    if (message.serverId !== "") {
      obj.serverId = message.serverId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStatsRequest>, I>>(base?: I): GetStatsRequest {
    return GetStatsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStatsRequest>, I>>(object: I): GetStatsRequest {
    const message = createBaseGetStatsRequest();
    message.serverId = object.serverId ?? "";
    return message;
  },
};

function createBaseServerStat(): ServerStat {
  return {
    id: "",
    serverId: "",
    averageResponseTime: 0,
    minResponseTime: 0,
    maxResponseTime: 0,
    pingCount: 0,
    successRate: 0,
    timestamp: "",
  };
}

export const ServerStat: MessageFns<ServerStat> = {
  encode(message: ServerStat, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.serverId !== "") {
      writer.uint32(18).string(message.serverId);
    }
    if (message.averageResponseTime !== 0) {
      writer.uint32(25).double(message.averageResponseTime);
    }
    if (message.minResponseTime !== 0) {
      writer.uint32(32).int64(message.minResponseTime);
    }
    if (message.maxResponseTime !== 0) {
      writer.uint32(40).int64(message.maxResponseTime);
    }
    if (message.pingCount !== 0) {
      writer.uint32(48).int64(message.pingCount);
    }
    if (message.successRate !== 0) {
      writer.uint32(57).double(message.successRate);
    }
    if (message.timestamp !== "") {
      writer.uint32(66).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerStat {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerStat();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serverId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.averageResponseTime = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.minResponseTime = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.maxResponseTime = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.pingCount = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.successRate = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerStat {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      serverId: isSet(object.serverId) ? globalThis.String(object.serverId) : "",
      averageResponseTime: isSet(object.averageResponseTime) ? globalThis.Number(object.averageResponseTime) : 0,
      minResponseTime: isSet(object.minResponseTime) ? globalThis.Number(object.minResponseTime) : 0,
      maxResponseTime: isSet(object.maxResponseTime) ? globalThis.Number(object.maxResponseTime) : 0,
      pingCount: isSet(object.pingCount) ? globalThis.Number(object.pingCount) : 0,
      successRate: isSet(object.successRate) ? globalThis.Number(object.successRate) : 0,
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: ServerStat): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.serverId !== "") {
      obj.serverId = message.serverId;
    }
    if (message.averageResponseTime !== 0) {
      obj.averageResponseTime = message.averageResponseTime;
    }
    if (message.minResponseTime !== 0) {
      obj.minResponseTime = Math.round(message.minResponseTime);
    }
    if (message.maxResponseTime !== 0) {
      obj.maxResponseTime = Math.round(message.maxResponseTime);
    }
    if (message.pingCount !== 0) {
      obj.pingCount = Math.round(message.pingCount);
    }
    if (message.successRate !== 0) {
      obj.successRate = message.successRate;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerStat>, I>>(base?: I): ServerStat {
    return ServerStat.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerStat>, I>>(object: I): ServerStat {
    const message = createBaseServerStat();
    message.id = object.id ?? "";
    message.serverId = object.serverId ?? "";
    message.averageResponseTime = object.averageResponseTime ?? 0;
    message.minResponseTime = object.minResponseTime ?? 0;
    message.maxResponseTime = object.maxResponseTime ?? 0;
    message.pingCount = object.pingCount ?? 0;
    message.successRate = object.successRate ?? 0;
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseGetStatsResponse(): GetStatsResponse {
  return { stats: [] };
}

export const GetStatsResponse: MessageFns<GetStatsResponse> = {
  encode(message: GetStatsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.stats) {
      ServerStat.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStatsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStatsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stats.push(ServerStat.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetStatsResponse {
    return {
      stats: globalThis.Array.isArray(object?.stats) ? object.stats.map((e: any) => ServerStat.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetStatsResponse): unknown {
    const obj: any = {};
    if (message.stats?.length) {
      obj.stats = message.stats.map((e) => ServerStat.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStatsResponse>, I>>(base?: I): GetStatsResponse {
    return GetStatsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStatsResponse>, I>>(object: I): GetStatsResponse {
    const message = createBaseGetStatsResponse();
    message.stats = object.stats?.map((e) => ServerStat.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetAccidentsRequest(): GetAccidentsRequest {
  return { serverId: "", startDate: "", endDate: "", resolved: false, page: 0, pageSize: 0 };
}

export const GetAccidentsRequest: MessageFns<GetAccidentsRequest> = {
  encode(message: GetAccidentsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverId !== "") {
      writer.uint32(10).string(message.serverId);
    }
    if (message.startDate !== "") {
      writer.uint32(18).string(message.startDate);
    }
    if (message.endDate !== "") {
      writer.uint32(26).string(message.endDate);
    }
    if (message.resolved !== false) {
      writer.uint32(32).bool(message.resolved);
    }
    if (message.page !== 0) {
      writer.uint32(40).int32(message.page);
    }
    if (message.pageSize !== 0) {
      writer.uint32(48).int32(message.pageSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAccidentsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAccidentsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.startDate = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.endDate = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.resolved = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAccidentsRequest {
    return {
      serverId: isSet(object.serverId) ? globalThis.String(object.serverId) : "",
      startDate: isSet(object.startDate) ? globalThis.String(object.startDate) : "",
      endDate: isSet(object.endDate) ? globalThis.String(object.endDate) : "",
      resolved: isSet(object.resolved) ? globalThis.Boolean(object.resolved) : false,
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      pageSize: isSet(object.pageSize) ? globalThis.Number(object.pageSize) : 0,
    };
  },

  toJSON(message: GetAccidentsRequest): unknown {
    const obj: any = {};
    if (message.serverId !== "") {
      obj.serverId = message.serverId;
    }
    if (message.startDate !== "") {
      obj.startDate = message.startDate;
    }
    if (message.endDate !== "") {
      obj.endDate = message.endDate;
    }
    if (message.resolved !== false) {
      obj.resolved = message.resolved;
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAccidentsRequest>, I>>(base?: I): GetAccidentsRequest {
    return GetAccidentsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAccidentsRequest>, I>>(object: I): GetAccidentsRequest {
    const message = createBaseGetAccidentsRequest();
    message.serverId = object.serverId ?? "";
    message.startDate = object.startDate ?? "";
    message.endDate = object.endDate ?? "";
    message.resolved = object.resolved ?? false;
    message.page = object.page ?? 0;
    message.pageSize = object.pageSize ?? 0;
    return message;
  },
};

function createBaseServerAccident(): ServerAccident {
  return { id: "", serverId: "", responseTime: 0, error: "", details: "", resolved: false, createdAt: "" };
}

export const ServerAccident: MessageFns<ServerAccident> = {
  encode(message: ServerAccident, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.serverId !== "") {
      writer.uint32(18).string(message.serverId);
    }
    if (message.responseTime !== 0) {
      writer.uint32(24).int64(message.responseTime);
    }
    if (message.error !== "") {
      writer.uint32(34).string(message.error);
    }
    if (message.details !== "") {
      writer.uint32(42).string(message.details);
    }
    if (message.resolved !== false) {
      writer.uint32(48).bool(message.resolved);
    }
    if (message.createdAt !== "") {
      writer.uint32(58).string(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerAccident {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerAccident();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serverId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.responseTime = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.details = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.resolved = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerAccident {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      serverId: isSet(object.serverId) ? globalThis.String(object.serverId) : "",
      responseTime: isSet(object.responseTime) ? globalThis.Number(object.responseTime) : 0,
      error: isSet(object.error) ? globalThis.String(object.error) : "",
      details: isSet(object.details) ? globalThis.String(object.details) : "",
      resolved: isSet(object.resolved) ? globalThis.Boolean(object.resolved) : false,
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
    };
  },

  toJSON(message: ServerAccident): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.serverId !== "") {
      obj.serverId = message.serverId;
    }
    if (message.responseTime !== 0) {
      obj.responseTime = Math.round(message.responseTime);
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    if (message.details !== "") {
      obj.details = message.details;
    }
    if (message.resolved !== false) {
      obj.resolved = message.resolved;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerAccident>, I>>(base?: I): ServerAccident {
    return ServerAccident.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerAccident>, I>>(object: I): ServerAccident {
    const message = createBaseServerAccident();
    message.id = object.id ?? "";
    message.serverId = object.serverId ?? "";
    message.responseTime = object.responseTime ?? 0;
    message.error = object.error ?? "";
    message.details = object.details ?? "";
    message.resolved = object.resolved ?? false;
    message.createdAt = object.createdAt ?? "";
    return message;
  },
};

function createBaseGetAccidentsResponse(): GetAccidentsResponse {
  return { accidents: [], totalCount: 0 };
}

export const GetAccidentsResponse: MessageFns<GetAccidentsResponse> = {
  encode(message: GetAccidentsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.accidents) {
      ServerAccident.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.totalCount !== 0) {
      writer.uint32(16).int64(message.totalCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAccidentsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAccidentsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accidents.push(ServerAccident.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalCount = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAccidentsResponse {
    return {
      accidents: globalThis.Array.isArray(object?.accidents)
        ? object.accidents.map((e: any) => ServerAccident.fromJSON(e))
        : [],
      totalCount: isSet(object.totalCount) ? globalThis.Number(object.totalCount) : 0,
    };
  },

  toJSON(message: GetAccidentsResponse): unknown {
    const obj: any = {};
    if (message.accidents?.length) {
      obj.accidents = message.accidents.map((e) => ServerAccident.toJSON(e));
    }
    if (message.totalCount !== 0) {
      obj.totalCount = Math.round(message.totalCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAccidentsResponse>, I>>(base?: I): GetAccidentsResponse {
    return GetAccidentsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAccidentsResponse>, I>>(object: I): GetAccidentsResponse {
    const message = createBaseGetAccidentsResponse();
    message.accidents = object.accidents?.map((e) => ServerAccident.fromPartial(e)) || [];
    message.totalCount = object.totalCount ?? 0;
    return message;
  },
};

function createBaseId(): Id {
  return { id: "" };
}

export const Id: MessageFns<Id> = {
  encode(message: Id, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Id {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Id {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: Id): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Id>, I>>(base?: I): Id {
    return Id.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Id>, I>>(object: I): Id {
    const message = createBaseId();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseServerResponse(): ServerResponse {
  return { status: 0, server: undefined, errors: [], error: undefined };
}

export const ServerResponse: MessageFns<ServerResponse> = {
  encode(message: ServerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.server !== undefined) {
      Server.encode(message.server, writer.uint32(18).fork()).join();
    }
    for (const v of message.errors) {
      ValidationError.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.error !== undefined) {
      writer.uint32(34).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.server = Server.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errors.push(ValidationError.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerResponse {
    return {
      status: isSet(object.status) ? statusCodeFromJSON(object.status) : 0,
      server: isSet(object.server) ? Server.fromJSON(object.server) : undefined,
      errors: globalThis.Array.isArray(object?.errors)
        ? object.errors.map((e: any) => ValidationError.fromJSON(e))
        : [],
      error: isSet(object.error) ? globalThis.String(object.error) : undefined,
    };
  },

  toJSON(message: ServerResponse): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = statusCodeToJSON(message.status);
    }
    if (message.server !== undefined) {
      obj.server = Server.toJSON(message.server);
    }
    if (message.errors?.length) {
      obj.errors = message.errors.map((e) => ValidationError.toJSON(e));
    }
    if (message.error !== undefined) {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerResponse>, I>>(base?: I): ServerResponse {
    return ServerResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerResponse>, I>>(object: I): ServerResponse {
    const message = createBaseServerResponse();
    message.status = object.status ?? 0;
    message.server = (object.server !== undefined && object.server !== null)
      ? Server.fromPartial(object.server)
      : undefined;
    message.errors = object.errors?.map((e) => ValidationError.fromPartial(e)) || [];
    message.error = object.error ?? undefined;
    return message;
  },
};

function createBaseServersResponse(): ServersResponse {
  return { status: 0, servers: [], errors: [], error: undefined };
}

export const ServersResponse: MessageFns<ServersResponse> = {
  encode(message: ServersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    for (const v of message.servers) {
      Server.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.errors) {
      ValidationError.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.error !== undefined) {
      writer.uint32(34).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.servers.push(Server.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errors.push(ValidationError.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServersResponse {
    return {
      status: isSet(object.status) ? statusCodeFromJSON(object.status) : 0,
      servers: globalThis.Array.isArray(object?.servers) ? object.servers.map((e: any) => Server.fromJSON(e)) : [],
      errors: globalThis.Array.isArray(object?.errors)
        ? object.errors.map((e: any) => ValidationError.fromJSON(e))
        : [],
      error: isSet(object.error) ? globalThis.String(object.error) : undefined,
    };
  },

  toJSON(message: ServersResponse): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = statusCodeToJSON(message.status);
    }
    if (message.servers?.length) {
      obj.servers = message.servers.map((e) => Server.toJSON(e));
    }
    if (message.errors?.length) {
      obj.errors = message.errors.map((e) => ValidationError.toJSON(e));
    }
    if (message.error !== undefined) {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServersResponse>, I>>(base?: I): ServersResponse {
    return ServersResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServersResponse>, I>>(object: I): ServersResponse {
    const message = createBaseServersResponse();
    message.status = object.status ?? 0;
    message.servers = object.servers?.map((e) => Server.fromPartial(e)) || [];
    message.errors = object.errors?.map((e) => ValidationError.fromPartial(e)) || [];
    message.error = object.error ?? undefined;
    return message;
  },
};

function createBaseServer(): Server {
  return {
    id: "",
    name: "",
    ipAddress: "",
    port: 0,
    protocol: "",
    credential: undefined,
    isRoot: 0,
    status: 0,
    agentStatus: 0,
    agentLogs: "",
  };
}

export const Server: MessageFns<Server> = {
  encode(message: Server, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.ipAddress !== "") {
      writer.uint32(26).string(message.ipAddress);
    }
    if (message.port !== 0) {
      writer.uint32(32).int32(message.port);
    }
    if (message.protocol !== "") {
      writer.uint32(42).string(message.protocol);
    }
    if (message.credential !== undefined) {
      ServerCredential.encode(message.credential, writer.uint32(50).fork()).join();
    }
    if (message.isRoot !== 0) {
      writer.uint32(56).int32(message.isRoot);
    }
    if (message.status !== 0) {
      writer.uint32(64).int32(message.status);
    }
    if (message.agentStatus !== 0) {
      writer.uint32(72).int32(message.agentStatus);
    }
    if (message.agentLogs !== "") {
      writer.uint32(82).string(message.agentLogs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Server {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ipAddress = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.port = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.protocol = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.credential = ServerCredential.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.isRoot = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.agentStatus = reader.int32() as any;
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.agentLogs = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Server {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      ipAddress: isSet(object.ipAddress) ? globalThis.String(object.ipAddress) : "",
      port: isSet(object.port) ? globalThis.Number(object.port) : 0,
      protocol: isSet(object.protocol) ? globalThis.String(object.protocol) : "",
      credential: isSet(object.credential) ? ServerCredential.fromJSON(object.credential) : undefined,
      isRoot: isSet(object.isRoot) ? globalThis.Number(object.isRoot) : 0,
      status: isSet(object.status) ? statusServerFromJSON(object.status) : 0,
      agentStatus: isSet(object.agentStatus) ? agentStatusServerFromJSON(object.agentStatus) : 0,
      agentLogs: isSet(object.agentLogs) ? globalThis.String(object.agentLogs) : "",
    };
  },

  toJSON(message: Server): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.ipAddress !== "") {
      obj.ipAddress = message.ipAddress;
    }
    if (message.port !== 0) {
      obj.port = Math.round(message.port);
    }
    if (message.protocol !== "") {
      obj.protocol = message.protocol;
    }
    if (message.credential !== undefined) {
      obj.credential = ServerCredential.toJSON(message.credential);
    }
    if (message.isRoot !== 0) {
      obj.isRoot = Math.round(message.isRoot);
    }
    if (message.status !== 0) {
      obj.status = statusServerToJSON(message.status);
    }
    if (message.agentStatus !== 0) {
      obj.agentStatus = agentStatusServerToJSON(message.agentStatus);
    }
    if (message.agentLogs !== "") {
      obj.agentLogs = message.agentLogs;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Server>, I>>(base?: I): Server {
    return Server.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Server>, I>>(object: I): Server {
    const message = createBaseServer();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.ipAddress = object.ipAddress ?? "";
    message.port = object.port ?? 0;
    message.protocol = object.protocol ?? "";
    message.credential = (object.credential !== undefined && object.credential !== null)
      ? ServerCredential.fromPartial(object.credential)
      : undefined;
    message.isRoot = object.isRoot ?? 0;
    message.status = object.status ?? 0;
    message.agentStatus = object.agentStatus ?? 0;
    message.agentLogs = object.agentLogs ?? "";
    return message;
  },
};

function createBaseServerCredential(): ServerCredential {
  return { username: "", password: undefined, sshKey: undefined };
}

export const ServerCredential: MessageFns<ServerCredential> = {
  encode(message: ServerCredential, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.password !== undefined) {
      writer.uint32(18).string(message.password);
    }
    if (message.sshKey !== undefined) {
      writer.uint32(26).string(message.sshKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerCredential {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerCredential();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sshKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerCredential {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : undefined,
      sshKey: isSet(object.sshKey) ? globalThis.String(object.sshKey) : undefined,
    };
  },

  toJSON(message: ServerCredential): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.password !== undefined) {
      obj.password = message.password;
    }
    if (message.sshKey !== undefined) {
      obj.sshKey = message.sshKey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerCredential>, I>>(base?: I): ServerCredential {
    return ServerCredential.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerCredential>, I>>(object: I): ServerCredential {
    const message = createBaseServerCredential();
    message.username = object.username ?? "";
    message.password = object.password ?? undefined;
    message.sshKey = object.sshKey ?? undefined;
    return message;
  },
};

function createBaseMessageResponse(): MessageResponse {
  return { status: 0, message: "" };
}

export const MessageResponse: MessageFns<MessageResponse> = {
  encode(message: MessageResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessageResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessageResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MessageResponse {
    return {
      status: isSet(object.status) ? statusCodeFromJSON(object.status) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: MessageResponse): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = statusCodeToJSON(message.status);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MessageResponse>, I>>(base?: I): MessageResponse {
    return MessageResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MessageResponse>, I>>(object: I): MessageResponse {
    const message = createBaseMessageResponse();
    message.status = object.status ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

export interface ServerService {
  Create(request: Server): Promise<ServerResponse>;
  Get(request: Id): Promise<ServerResponse>;
  All(request: Empty): Promise<ServersResponse>;
  Update(request: Server): Promise<ServerResponse>;
  Delete(request: Id): Promise<MessageResponse>;
  RetryConnection(request: Id): Promise<ServerResponse>;
  InstallAgent(request: Id): Promise<MessageResponse>;
  GetStats(request: GetStatsRequest): Promise<GetStatsResponse>;
  GetAccidents(request: GetAccidentsRequest): Promise<GetAccidentsResponse>;
  GetRealtimeStats(request: GetRealtimeStatsRequest): Promise<GetRealtimeStatsResponse>;
  ConfigureAgent(request: ConfigureAgentRequest): Promise<MessageResponse>;
  UpdateAgentPort(request: UpdateAgentPortRequest): Promise<MessageResponse>;
  UpdateServerTimeZone(request: UpdateServerTimeZoneRequest): Promise<MessageResponse>;
}

export const ServerServiceServiceName = "controlplane.ServerService";
export class ServerServiceClientImpl implements ServerService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || ServerServiceServiceName;
    this.rpc = rpc;
    this.Create = this.Create.bind(this);
    this.Get = this.Get.bind(this);
    this.All = this.All.bind(this);
    this.Update = this.Update.bind(this);
    this.Delete = this.Delete.bind(this);
    this.RetryConnection = this.RetryConnection.bind(this);
    this.InstallAgent = this.InstallAgent.bind(this);
    this.GetStats = this.GetStats.bind(this);
    this.GetAccidents = this.GetAccidents.bind(this);
    this.GetRealtimeStats = this.GetRealtimeStats.bind(this);
    this.ConfigureAgent = this.ConfigureAgent.bind(this);
    this.UpdateAgentPort = this.UpdateAgentPort.bind(this);
    this.UpdateServerTimeZone = this.UpdateServerTimeZone.bind(this);
  }
  Create(request: Server): Promise<ServerResponse> {
    const data = Server.encode(request).finish();
    const promise = this.rpc.request(this.service, "Create", data);
    return promise.then((data) => ServerResponse.decode(new BinaryReader(data)));
  }

  Get(request: Id): Promise<ServerResponse> {
    const data = Id.encode(request).finish();
    const promise = this.rpc.request(this.service, "Get", data);
    return promise.then((data) => ServerResponse.decode(new BinaryReader(data)));
  }

  All(request: Empty): Promise<ServersResponse> {
    const data = Empty.encode(request).finish();
    const promise = this.rpc.request(this.service, "All", data);
    return promise.then((data) => ServersResponse.decode(new BinaryReader(data)));
  }

  Update(request: Server): Promise<ServerResponse> {
    const data = Server.encode(request).finish();
    const promise = this.rpc.request(this.service, "Update", data);
    return promise.then((data) => ServerResponse.decode(new BinaryReader(data)));
  }

  Delete(request: Id): Promise<MessageResponse> {
    const data = Id.encode(request).finish();
    const promise = this.rpc.request(this.service, "Delete", data);
    return promise.then((data) => MessageResponse.decode(new BinaryReader(data)));
  }

  RetryConnection(request: Id): Promise<ServerResponse> {
    const data = Id.encode(request).finish();
    const promise = this.rpc.request(this.service, "RetryConnection", data);
    return promise.then((data) => ServerResponse.decode(new BinaryReader(data)));
  }

  InstallAgent(request: Id): Promise<MessageResponse> {
    const data = Id.encode(request).finish();
    const promise = this.rpc.request(this.service, "InstallAgent", data);
    return promise.then((data) => MessageResponse.decode(new BinaryReader(data)));
  }

  GetStats(request: GetStatsRequest): Promise<GetStatsResponse> {
    const data = GetStatsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetStats", data);
    return promise.then((data) => GetStatsResponse.decode(new BinaryReader(data)));
  }

  GetAccidents(request: GetAccidentsRequest): Promise<GetAccidentsResponse> {
    const data = GetAccidentsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetAccidents", data);
    return promise.then((data) => GetAccidentsResponse.decode(new BinaryReader(data)));
  }

  GetRealtimeStats(request: GetRealtimeStatsRequest): Promise<GetRealtimeStatsResponse> {
    const data = GetRealtimeStatsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetRealtimeStats", data);
    return promise.then((data) => GetRealtimeStatsResponse.decode(new BinaryReader(data)));
  }

  ConfigureAgent(request: ConfigureAgentRequest): Promise<MessageResponse> {
    const data = ConfigureAgentRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ConfigureAgent", data);
    return promise.then((data) => MessageResponse.decode(new BinaryReader(data)));
  }

  UpdateAgentPort(request: UpdateAgentPortRequest): Promise<MessageResponse> {
    const data = UpdateAgentPortRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateAgentPort", data);
    return promise.then((data) => MessageResponse.decode(new BinaryReader(data)));
  }

  UpdateServerTimeZone(request: UpdateServerTimeZoneRequest): Promise<MessageResponse> {
    const data = UpdateServerTimeZoneRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateServerTimeZone", data);
    return promise.then((data) => MessageResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
