// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: server/server.proto

package server

import (
	common "github.com/zhinea/sylix/internal/infra/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_UNSPECIFIED       StatusCode = 0
	StatusCode_OK                StatusCode = 200
	StatusCode_CREATED           StatusCode = 201
	StatusCode_NOT_FOUND         StatusCode = 404
	StatusCode_INTERNAL_ERROR    StatusCode = 500
	StatusCode_BAD_REQUEST       StatusCode = 400
	StatusCode_VALIDATION_FAILED StatusCode = 402
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:   "UNSPECIFIED",
		200: "OK",
		201: "CREATED",
		404: "NOT_FOUND",
		500: "INTERNAL_ERROR",
		400: "BAD_REQUEST",
		402: "VALIDATION_FAILED",
	}
	StatusCode_value = map[string]int32{
		"UNSPECIFIED":       0,
		"OK":                200,
		"CREATED":           201,
		"NOT_FOUND":         404,
		"INTERNAL_ERROR":    500,
		"BAD_REQUEST":       400,
		"VALIDATION_FAILED": 402,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_server_server_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_server_server_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_server_server_proto_rawDescGZIP(), []int{0}
}

// Status dimana hanya untuk koneksi ke server, apakah koneksi berhasil atau tidak
type StatusServer int32

const (
	StatusServer_STATUS_SERVER_UNSPECIFIED StatusServer = 0
	StatusServer_CONNECTED                 StatusServer = 1
	StatusServer_DISCONNECTED              StatusServer = 2
)

// Enum value maps for StatusServer.
var (
	StatusServer_name = map[int32]string{
		0: "STATUS_SERVER_UNSPECIFIED",
		1: "CONNECTED",
		2: "DISCONNECTED",
	}
	StatusServer_value = map[string]int32{
		"STATUS_SERVER_UNSPECIFIED": 0,
		"CONNECTED":                 1,
		"DISCONNECTED":              2,
	}
)

func (x StatusServer) Enum() *StatusServer {
	p := new(StatusServer)
	*p = x
	return p
}

func (x StatusServer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusServer) Descriptor() protoreflect.EnumDescriptor {
	return file_server_server_proto_enumTypes[1].Descriptor()
}

func (StatusServer) Type() protoreflect.EnumType {
	return &file_server_server_proto_enumTypes[1]
}

func (x StatusServer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusServer.Descriptor instead.
func (StatusServer) EnumDescriptor() ([]byte, []int) {
	return file_server_server_proto_rawDescGZIP(), []int{1}
}

type AgentStatusServer int32

const (
	AgentStatusServer_AGENT_STATUS_SERVER_UNSPECIFIED AgentStatusServer = 0
	AgentStatusServer_INSTALLING                      AgentStatusServer = 1
	AgentStatusServer_CONFIGURING                     AgentStatusServer = 2
	AgentStatusServer_FINALIZING_SETUP                AgentStatusServer = 3
	AgentStatusServer_SUCCESS                         AgentStatusServer = 4
	AgentStatusServer_FAILED                          AgentStatusServer = 5
)

// Enum value maps for AgentStatusServer.
var (
	AgentStatusServer_name = map[int32]string{
		0: "AGENT_STATUS_SERVER_UNSPECIFIED",
		1: "INSTALLING",
		2: "CONFIGURING",
		3: "FINALIZING_SETUP",
		4: "SUCCESS",
		5: "FAILED",
	}
	AgentStatusServer_value = map[string]int32{
		"AGENT_STATUS_SERVER_UNSPECIFIED": 0,
		"INSTALLING":                      1,
		"CONFIGURING":                     2,
		"FINALIZING_SETUP":                3,
		"SUCCESS":                         4,
		"FAILED":                          5,
	}
)

func (x AgentStatusServer) Enum() *AgentStatusServer {
	p := new(AgentStatusServer)
	*p = x
	return p
}

func (x AgentStatusServer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatusServer) Descriptor() protoreflect.EnumDescriptor {
	return file_server_server_proto_enumTypes[2].Descriptor()
}

func (AgentStatusServer) Type() protoreflect.EnumType {
	return &file_server_server_proto_enumTypes[2]
}

func (x AgentStatusServer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatusServer.Descriptor instead.
func (AgentStatusServer) EnumDescriptor() ([]byte, []int) {
	return file_server_server_proto_rawDescGZIP(), []int{2}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_server_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_server_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_server_server_proto_rawDescGZIP(), []int{0}
}

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_server_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_server_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_server_server_proto_rawDescGZIP(), []int{1}
}

func (x *Id) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ServerResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        StatusCode                `protobuf:"varint,1,opt,name=status,proto3,enum=server.StatusCode" json:"status,omitempty"`
	Server        *Server                   `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Errors        []*common.ValidationError `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Error         *string                   `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	mi := &file_server_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_server_server_proto_rawDescGZIP(), []int{2}
}

func (x *ServerResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_UNSPECIFIED
}

func (x *ServerResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ServerResponse) GetErrors() []*common.ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ServerResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ServersResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        StatusCode                `protobuf:"varint,1,opt,name=status,proto3,enum=server.StatusCode" json:"status,omitempty"`
	Servers       []*Server                 `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	Errors        []*common.ValidationError `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Error         *string                   `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServersResponse) Reset() {
	*x = ServersResponse{}
	mi := &file_server_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersResponse) ProtoMessage() {}

func (x *ServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersResponse.ProtoReflect.Descriptor instead.
func (*ServersResponse) Descriptor() ([]byte, []int) {
	return file_server_server_proto_rawDescGZIP(), []int{3}
}

func (x *ServersResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_UNSPECIFIED
}

func (x *ServersResponse) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ServersResponse) GetErrors() []*common.ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ServersResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Credential    *ServerCredential      `protobuf:"bytes,6,opt,name=credential,proto3" json:"credential,omitempty"`
	IsRoot        int32                  `protobuf:"varint,7,opt,name=isRoot,proto3" json:"isRoot,omitempty"`
	Status        StatusServer           `protobuf:"varint,8,opt,name=status,proto3,enum=server.StatusServer" json:"status,omitempty"`
	AgentStatus   AgentStatusServer      `protobuf:"varint,9,opt,name=agentStatus,proto3,enum=server.AgentStatusServer" json:"agentStatus,omitempty"`
	AgentLogs     string                 `protobuf:"bytes,10,opt,name=agentLogs,proto3" json:"agentLogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_server_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_server_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_server_server_proto_rawDescGZIP(), []int{4}
}

func (x *Server) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Server) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Server) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Server) GetCredential() *ServerCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *Server) GetIsRoot() int32 {
	if x != nil {
		return x.IsRoot
	}
	return 0
}

func (x *Server) GetStatus() StatusServer {
	if x != nil {
		return x.Status
	}
	return StatusServer_STATUS_SERVER_UNSPECIFIED
}

func (x *Server) GetAgentStatus() AgentStatusServer {
	if x != nil {
		return x.AgentStatus
	}
	return AgentStatusServer_AGENT_STATUS_SERVER_UNSPECIFIED
}

func (x *Server) GetAgentLogs() string {
	if x != nil {
		return x.AgentLogs
	}
	return ""
}

type ServerCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	SshKey        *string                `protobuf:"bytes,3,opt,name=sshKey,proto3,oneof" json:"sshKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCredential) Reset() {
	*x = ServerCredential{}
	mi := &file_server_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCredential) ProtoMessage() {}

func (x *ServerCredential) ProtoReflect() protoreflect.Message {
	mi := &file_server_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCredential.ProtoReflect.Descriptor instead.
func (*ServerCredential) Descriptor() ([]byte, []int) {
	return file_server_server_proto_rawDescGZIP(), []int{5}
}

func (x *ServerCredential) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ServerCredential) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *ServerCredential) GetSshKey() string {
	if x != nil && x.SshKey != nil {
		return *x.SshKey
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=server.StatusCode" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_server_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_server_server_proto_rawDescGZIP(), []int{6}
}

func (x *MessageResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_UNSPECIFIED
}

func (x *MessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_server_server_proto protoreflect.FileDescriptor

const file_server_server_proto_rawDesc = "" +
	"\n" +
	"\x13server/server.proto\x12\x06server\x1a\x17common/validation.proto\"\a\n" +
	"\x05Empty\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xba\x01\n" +
	"\x0eServerResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.server.StatusCodeR\x06status\x12&\n" +
	"\x06server\x18\x02 \x01(\v2\x0e.server.ServerR\x06server\x12/\n" +
	"\x06errors\x18\x03 \x03(\v2\x17.common.ValidationErrorR\x06errors\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xbd\x01\n" +
	"\x0fServersResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.server.StatusCodeR\x06status\x12(\n" +
	"\aservers\x18\x02 \x03(\v2\x0e.server.ServerR\aservers\x12/\n" +
	"\x06errors\x18\x03 \x03(\v2\x17.common.ValidationErrorR\x06errors\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xd5\x02\n" +
	"\x06Server\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tipAddress\x18\x03 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x128\n" +
	"\n" +
	"credential\x18\x06 \x01(\v2\x18.server.ServerCredentialR\n" +
	"credential\x12\x16\n" +
	"\x06isRoot\x18\a \x01(\x05R\x06isRoot\x12,\n" +
	"\x06status\x18\b \x01(\x0e2\x14.server.StatusServerR\x06status\x12;\n" +
	"\vagentStatus\x18\t \x01(\x0e2\x19.server.AgentStatusServerR\vagentStatus\x12\x1c\n" +
	"\tagentLogs\x18\n" +
	" \x01(\tR\tagentLogs\"\x84\x01\n" +
	"\x10ServerCredential\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tH\x00R\bpassword\x88\x01\x01\x12\x1b\n" +
	"\x06sshKey\x18\x03 \x01(\tH\x01R\x06sshKey\x88\x01\x01B\v\n" +
	"\t_passwordB\t\n" +
	"\a_sshKey\"W\n" +
	"\x0fMessageResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.server.StatusCodeR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x83\x01\n" +
	"\n" +
	"StatusCode\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\a\n" +
	"\x02OK\x10\xc8\x01\x12\f\n" +
	"\aCREATED\x10\xc9\x01\x12\x0e\n" +
	"\tNOT_FOUND\x10\x94\x03\x12\x13\n" +
	"\x0eINTERNAL_ERROR\x10\xf4\x03\x12\x10\n" +
	"\vBAD_REQUEST\x10\x90\x03\x12\x16\n" +
	"\x11VALIDATION_FAILED\x10\x92\x03*N\n" +
	"\fStatusServer\x12\x1d\n" +
	"\x19STATUS_SERVER_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCONNECTED\x10\x01\x12\x10\n" +
	"\fDISCONNECTED\x10\x02*\x88\x01\n" +
	"\x11AgentStatusServer\x12#\n" +
	"\x1fAGENT_STATUS_SERVER_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"INSTALLING\x10\x01\x12\x0f\n" +
	"\vCONFIGURING\x10\x02\x12\x14\n" +
	"\x10FINALIZING_SETUP\x10\x03\x12\v\n" +
	"\aSUCCESS\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x052\xb1\x02\n" +
	"\rServerService\x120\n" +
	"\x06Create\x12\x0e.server.Server\x1a\x16.server.ServerResponse\x12)\n" +
	"\x03Get\x12\n" +
	".server.Id\x1a\x16.server.ServerResponse\x12-\n" +
	"\x03All\x12\r.server.Empty\x1a\x17.server.ServersResponse\x120\n" +
	"\x06Update\x12\x0e.server.Server\x1a\x16.server.ServerResponse\x12-\n" +
	"\x06Delete\x12\n" +
	".server.Id\x1a\x17.server.MessageResponse\x123\n" +
	"\fInstallAgent\x12\n" +
	".server.Id\x1a\x17.server.MessageResponseB5Z3github.com/zhinea/sylix/internal/infra/proto/serverb\x06proto3"

var (
	file_server_server_proto_rawDescOnce sync.Once
	file_server_server_proto_rawDescData []byte
)

func file_server_server_proto_rawDescGZIP() []byte {
	file_server_server_proto_rawDescOnce.Do(func() {
		file_server_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_server_proto_rawDesc), len(file_server_server_proto_rawDesc)))
	})
	return file_server_server_proto_rawDescData
}

var file_server_server_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_server_server_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_server_server_proto_goTypes = []any{
	(StatusCode)(0),                // 0: server.StatusCode
	(StatusServer)(0),              // 1: server.StatusServer
	(AgentStatusServer)(0),         // 2: server.AgentStatusServer
	(*Empty)(nil),                  // 3: server.Empty
	(*Id)(nil),                     // 4: server.Id
	(*ServerResponse)(nil),         // 5: server.ServerResponse
	(*ServersResponse)(nil),        // 6: server.ServersResponse
	(*Server)(nil),                 // 7: server.Server
	(*ServerCredential)(nil),       // 8: server.ServerCredential
	(*MessageResponse)(nil),        // 9: server.MessageResponse
	(*common.ValidationError)(nil), // 10: common.ValidationError
}
var file_server_server_proto_depIdxs = []int32{
	0,  // 0: server.ServerResponse.status:type_name -> server.StatusCode
	7,  // 1: server.ServerResponse.server:type_name -> server.Server
	10, // 2: server.ServerResponse.errors:type_name -> common.ValidationError
	0,  // 3: server.ServersResponse.status:type_name -> server.StatusCode
	7,  // 4: server.ServersResponse.servers:type_name -> server.Server
	10, // 5: server.ServersResponse.errors:type_name -> common.ValidationError
	8,  // 6: server.Server.credential:type_name -> server.ServerCredential
	1,  // 7: server.Server.status:type_name -> server.StatusServer
	2,  // 8: server.Server.agentStatus:type_name -> server.AgentStatusServer
	0,  // 9: server.MessageResponse.status:type_name -> server.StatusCode
	7,  // 10: server.ServerService.Create:input_type -> server.Server
	4,  // 11: server.ServerService.Get:input_type -> server.Id
	3,  // 12: server.ServerService.All:input_type -> server.Empty
	7,  // 13: server.ServerService.Update:input_type -> server.Server
	4,  // 14: server.ServerService.Delete:input_type -> server.Id
	4,  // 15: server.ServerService.InstallAgent:input_type -> server.Id
	5,  // 16: server.ServerService.Create:output_type -> server.ServerResponse
	5,  // 17: server.ServerService.Get:output_type -> server.ServerResponse
	6,  // 18: server.ServerService.All:output_type -> server.ServersResponse
	5,  // 19: server.ServerService.Update:output_type -> server.ServerResponse
	9,  // 20: server.ServerService.Delete:output_type -> server.MessageResponse
	9,  // 21: server.ServerService.InstallAgent:output_type -> server.MessageResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_server_server_proto_init() }
func file_server_server_proto_init() {
	if File_server_server_proto != nil {
		return
	}
	file_server_server_proto_msgTypes[2].OneofWrappers = []any{}
	file_server_server_proto_msgTypes[3].OneofWrappers = []any{}
	file_server_server_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_server_proto_rawDesc), len(file_server_server_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_server_proto_goTypes,
		DependencyIndexes: file_server_server_proto_depIdxs,
		EnumInfos:         file_server_server_proto_enumTypes,
		MessageInfos:      file_server_server_proto_msgTypes,
	}.Build()
	File_server_server_proto = out.File
	file_server_server_proto_goTypes = nil
	file_server_server_proto_depIdxs = nil
}
