// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: controlplane/nodes/nodes.proto

package nodes

import (
	common "github.com/zhinea/sylix/internal/infra/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	PriorityStartup int32                  `protobuf:"varint,5,opt,name=priority_startup,json=priorityStartup,proto3" json:"priority_startup,omitempty"`
	Fields          string                 `protobuf:"bytes,6,opt,name=fields,proto3" json:"fields,omitempty"`
	Imports         string                 `protobuf:"bytes,7,opt,name=imports,proto3" json:"imports,omitempty"`
	Exports         string                 `protobuf:"bytes,8,opt,name=exports,proto3" json:"exports,omitempty"`
	ServerId        string                 `protobuf:"bytes,9,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_controlplane_nodes_nodes_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Node) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Node) GetPriorityStartup() int32 {
	if x != nil {
		return x.PriorityStartup
	}
	return 0
}

func (x *Node) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

func (x *Node) GetImports() string {
	if x != nil {
		return x.Imports
	}
	return ""
}

func (x *Node) GetExports() string {
	if x != nil {
		return x.Exports
	}
	return ""
}

func (x *Node) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Node) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Node) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateNodeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type            string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	PriorityStartup int32                  `protobuf:"varint,4,opt,name=priority_startup,json=priorityStartup,proto3" json:"priority_startup,omitempty"`
	Fields          string                 `protobuf:"bytes,5,opt,name=fields,proto3" json:"fields,omitempty"`
	Imports         string                 `protobuf:"bytes,6,opt,name=imports,proto3" json:"imports,omitempty"`
	Exports         string                 `protobuf:"bytes,7,opt,name=exports,proto3" json:"exports,omitempty"`
	ServerId        string                 `protobuf:"bytes,8,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_nodes_nodes_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNodeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateNodeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateNodeRequest) GetPriorityStartup() int32 {
	if x != nil {
		return x.PriorityStartup
	}
	return 0
}

func (x *CreateNodeRequest) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

func (x *CreateNodeRequest) GetImports() string {
	if x != nil {
		return x.Imports
	}
	return ""
}

func (x *CreateNodeRequest) GetExports() string {
	if x != nil {
		return x.Exports
	}
	return ""
}

func (x *CreateNodeRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_nodes_nodes_proto_rawDescGZIP(), []int{2}
}

func (x *GetNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_nodes_nodes_proto_rawDescGZIP(), []int{3}
}

func (x *ListNodesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNodesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateNodeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	PriorityStartup int32                  `protobuf:"varint,5,opt,name=priority_startup,json=priorityStartup,proto3" json:"priority_startup,omitempty"`
	Fields          string                 `protobuf:"bytes,6,opt,name=fields,proto3" json:"fields,omitempty"`
	Imports         string                 `protobuf:"bytes,7,opt,name=imports,proto3" json:"imports,omitempty"`
	Exports         string                 `protobuf:"bytes,8,opt,name=exports,proto3" json:"exports,omitempty"`
	ServerId        string                 `protobuf:"bytes,9,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateNodeRequest) Reset() {
	*x = UpdateNodeRequest{}
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeRequest) ProtoMessage() {}

func (x *UpdateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_nodes_nodes_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateNodeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateNodeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateNodeRequest) GetPriorityStartup() int32 {
	if x != nil {
		return x.PriorityStartup
	}
	return 0
}

func (x *UpdateNodeRequest) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

func (x *UpdateNodeRequest) GetImports() string {
	if x != nil {
		return x.Imports
	}
	return ""
}

func (x *UpdateNodeRequest) GetExports() string {
	if x != nil {
		return x.Exports
	}
	return ""
}

func (x *UpdateNodeRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type DeleteNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_nodes_nodes_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeployNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployNodeRequest) Reset() {
	*x = DeployNodeRequest{}
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployNodeRequest) ProtoMessage() {}

func (x *DeployNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployNodeRequest.ProtoReflect.Descriptor instead.
func (*DeployNodeRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_nodes_nodes_proto_rawDescGZIP(), []int{6}
}

func (x *DeployNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetNodeGraphStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeGraphStatusRequest) Reset() {
	*x = GetNodeGraphStatusRequest{}
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeGraphStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeGraphStatusRequest) ProtoMessage() {}

func (x *GetNodeGraphStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeGraphStatusRequest.ProtoReflect.Descriptor instead.
func (*GetNodeGraphStatusRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_nodes_nodes_proto_rawDescGZIP(), []int{7}
}

func (x *GetNodeGraphStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetNodeGraphStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Logs          string                 `protobuf:"bytes,2,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeGraphStatusResponse) Reset() {
	*x = GetNodeGraphStatusResponse{}
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeGraphStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeGraphStatusResponse) ProtoMessage() {}

func (x *GetNodeGraphStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeGraphStatusResponse.ProtoReflect.Descriptor instead.
func (*GetNodeGraphStatusResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_nodes_nodes_proto_rawDescGZIP(), []int{8}
}

func (x *GetNodeGraphStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetNodeGraphStatusResponse) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

type NodeResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        common.StatusCode         `protobuf:"varint,1,opt,name=status,proto3,enum=common.StatusCode" json:"status,omitempty"`
	Node          *Node                     `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Errors        []*common.ValidationError `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Error         string                    `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResponse) Reset() {
	*x = NodeResponse{}
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResponse) ProtoMessage() {}

func (x *NodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResponse.ProtoReflect.Descriptor instead.
func (*NodeResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_nodes_nodes_proto_rawDescGZIP(), []int{9}
}

func (x *NodeResponse) GetStatus() common.StatusCode {
	if x != nil {
		return x.Status
	}
	return common.StatusCode(0)
}

func (x *NodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeResponse) GetErrors() []*common.ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *NodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListNodesResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        common.StatusCode         `protobuf:"varint,1,opt,name=status,proto3,enum=common.StatusCode" json:"status,omitempty"`
	Nodes         []*Node                   `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	TotalCount    int64                     `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Errors        []*common.ValidationError `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	Error         string                    `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_nodes_nodes_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_nodes_nodes_proto_rawDescGZIP(), []int{10}
}

func (x *ListNodesResponse) GetStatus() common.StatusCode {
	if x != nil {
		return x.Status
	}
	return common.StatusCode(0)
}

func (x *ListNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListNodesResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListNodesResponse) GetErrors() []*common.ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ListNodesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_controlplane_nodes_nodes_proto protoreflect.FileDescriptor

const file_controlplane_nodes_nodes_proto_rawDesc = "" +
	"\n" +
	"\x1econtrolplane/nodes/nodes.proto\x12\x12controlplane.nodes\x1a\x17common/validation.proto\x1a\x13common/common.proto\"\xb2\x02\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12)\n" +
	"\x10priority_startup\x18\x05 \x01(\x05R\x0fpriorityStartup\x12\x16\n" +
	"\x06fields\x18\x06 \x01(\tR\x06fields\x12\x18\n" +
	"\aimports\x18\a \x01(\tR\aimports\x12\x18\n" +
	"\aexports\x18\b \x01(\tR\aexports\x12\x1b\n" +
	"\tserver_id\x18\t \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"\xf1\x01\n" +
	"\x11CreateNodeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12)\n" +
	"\x10priority_startup\x18\x04 \x01(\x05R\x0fpriorityStartup\x12\x16\n" +
	"\x06fields\x18\x05 \x01(\tR\x06fields\x12\x18\n" +
	"\aimports\x18\x06 \x01(\tR\aimports\x12\x18\n" +
	"\aexports\x18\a \x01(\tR\aexports\x12\x1b\n" +
	"\tserver_id\x18\b \x01(\tR\bserverId\" \n" +
	"\x0eGetNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x10ListNodesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x81\x02\n" +
	"\x11UpdateNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12)\n" +
	"\x10priority_startup\x18\x05 \x01(\x05R\x0fpriorityStartup\x12\x16\n" +
	"\x06fields\x18\x06 \x01(\tR\x06fields\x12\x18\n" +
	"\aimports\x18\a \x01(\tR\aimports\x12\x18\n" +
	"\aexports\x18\b \x01(\tR\aexports\x12\x1b\n" +
	"\tserver_id\x18\t \x01(\tR\bserverId\"#\n" +
	"\x11DeleteNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11DeployNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x19GetNodeGraphStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x1aGetNodeGraphStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04logs\x18\x02 \x01(\tR\x04logs\"\xaf\x01\n" +
	"\fNodeResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.common.StatusCodeR\x06status\x12,\n" +
	"\x04node\x18\x02 \x01(\v2\x18.controlplane.nodes.NodeR\x04node\x12/\n" +
	"\x06errors\x18\x03 \x03(\v2\x17.common.ValidationErrorR\x06errors\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xd7\x01\n" +
	"\x11ListNodesResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.common.StatusCodeR\x06status\x12.\n" +
	"\x05nodes\x18\x02 \x03(\v2\x18.controlplane.nodes.NodeR\x05nodes\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x12/\n" +
	"\x06errors\x18\x04 \x03(\v2\x17.common.ValidationErrorR\x06errors\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2\xf7\x04\n" +
	"\vNodeService\x12U\n" +
	"\n" +
	"CreateNode\x12%.controlplane.nodes.CreateNodeRequest\x1a .controlplane.nodes.NodeResponse\x12O\n" +
	"\aGetNode\x12\".controlplane.nodes.GetNodeRequest\x1a .controlplane.nodes.NodeResponse\x12X\n" +
	"\tListNodes\x12$.controlplane.nodes.ListNodesRequest\x1a%.controlplane.nodes.ListNodesResponse\x12U\n" +
	"\n" +
	"UpdateNode\x12%.controlplane.nodes.UpdateNodeRequest\x1a .controlplane.nodes.NodeResponse\x12L\n" +
	"\n" +
	"DeleteNode\x12%.controlplane.nodes.DeleteNodeRequest\x1a\x17.common.MessageResponse\x12s\n" +
	"\x12GetNodeGraphStatus\x12-.controlplane.nodes.GetNodeGraphStatusRequest\x1a..controlplane.nodes.GetNodeGraphStatusResponse\x12L\n" +
	"\n" +
	"DeployNode\x12%.controlplane.nodes.DeployNodeRequest\x1a\x17.common.MessageResponseBAZ?github.com/zhinea/sylix/internal/infra/proto/controlplane/nodesb\x06proto3"

var (
	file_controlplane_nodes_nodes_proto_rawDescOnce sync.Once
	file_controlplane_nodes_nodes_proto_rawDescData []byte
)

func file_controlplane_nodes_nodes_proto_rawDescGZIP() []byte {
	file_controlplane_nodes_nodes_proto_rawDescOnce.Do(func() {
		file_controlplane_nodes_nodes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_nodes_nodes_proto_rawDesc), len(file_controlplane_nodes_nodes_proto_rawDesc)))
	})
	return file_controlplane_nodes_nodes_proto_rawDescData
}

var file_controlplane_nodes_nodes_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_controlplane_nodes_nodes_proto_goTypes = []any{
	(*Node)(nil),                       // 0: controlplane.nodes.Node
	(*CreateNodeRequest)(nil),          // 1: controlplane.nodes.CreateNodeRequest
	(*GetNodeRequest)(nil),             // 2: controlplane.nodes.GetNodeRequest
	(*ListNodesRequest)(nil),           // 3: controlplane.nodes.ListNodesRequest
	(*UpdateNodeRequest)(nil),          // 4: controlplane.nodes.UpdateNodeRequest
	(*DeleteNodeRequest)(nil),          // 5: controlplane.nodes.DeleteNodeRequest
	(*DeployNodeRequest)(nil),          // 6: controlplane.nodes.DeployNodeRequest
	(*GetNodeGraphStatusRequest)(nil),  // 7: controlplane.nodes.GetNodeGraphStatusRequest
	(*GetNodeGraphStatusResponse)(nil), // 8: controlplane.nodes.GetNodeGraphStatusResponse
	(*NodeResponse)(nil),               // 9: controlplane.nodes.NodeResponse
	(*ListNodesResponse)(nil),          // 10: controlplane.nodes.ListNodesResponse
	(common.StatusCode)(0),             // 11: common.StatusCode
	(*common.ValidationError)(nil),     // 12: common.ValidationError
	(*common.MessageResponse)(nil),     // 13: common.MessageResponse
}
var file_controlplane_nodes_nodes_proto_depIdxs = []int32{
	11, // 0: controlplane.nodes.NodeResponse.status:type_name -> common.StatusCode
	0,  // 1: controlplane.nodes.NodeResponse.node:type_name -> controlplane.nodes.Node
	12, // 2: controlplane.nodes.NodeResponse.errors:type_name -> common.ValidationError
	11, // 3: controlplane.nodes.ListNodesResponse.status:type_name -> common.StatusCode
	0,  // 4: controlplane.nodes.ListNodesResponse.nodes:type_name -> controlplane.nodes.Node
	12, // 5: controlplane.nodes.ListNodesResponse.errors:type_name -> common.ValidationError
	1,  // 6: controlplane.nodes.NodeService.CreateNode:input_type -> controlplane.nodes.CreateNodeRequest
	2,  // 7: controlplane.nodes.NodeService.GetNode:input_type -> controlplane.nodes.GetNodeRequest
	3,  // 8: controlplane.nodes.NodeService.ListNodes:input_type -> controlplane.nodes.ListNodesRequest
	4,  // 9: controlplane.nodes.NodeService.UpdateNode:input_type -> controlplane.nodes.UpdateNodeRequest
	5,  // 10: controlplane.nodes.NodeService.DeleteNode:input_type -> controlplane.nodes.DeleteNodeRequest
	7,  // 11: controlplane.nodes.NodeService.GetNodeGraphStatus:input_type -> controlplane.nodes.GetNodeGraphStatusRequest
	6,  // 12: controlplane.nodes.NodeService.DeployNode:input_type -> controlplane.nodes.DeployNodeRequest
	9,  // 13: controlplane.nodes.NodeService.CreateNode:output_type -> controlplane.nodes.NodeResponse
	9,  // 14: controlplane.nodes.NodeService.GetNode:output_type -> controlplane.nodes.NodeResponse
	10, // 15: controlplane.nodes.NodeService.ListNodes:output_type -> controlplane.nodes.ListNodesResponse
	9,  // 16: controlplane.nodes.NodeService.UpdateNode:output_type -> controlplane.nodes.NodeResponse
	13, // 17: controlplane.nodes.NodeService.DeleteNode:output_type -> common.MessageResponse
	8,  // 18: controlplane.nodes.NodeService.GetNodeGraphStatus:output_type -> controlplane.nodes.GetNodeGraphStatusResponse
	13, // 19: controlplane.nodes.NodeService.DeployNode:output_type -> common.MessageResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_controlplane_nodes_nodes_proto_init() }
func file_controlplane_nodes_nodes_proto_init() {
	if File_controlplane_nodes_nodes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_nodes_nodes_proto_rawDesc), len(file_controlplane_nodes_nodes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_nodes_nodes_proto_goTypes,
		DependencyIndexes: file_controlplane_nodes_nodes_proto_depIdxs,
		MessageInfos:      file_controlplane_nodes_nodes_proto_msgTypes,
	}.Build()
	File_controlplane_nodes_nodes_proto = out.File
	file_controlplane_nodes_nodes_proto_goTypes = nil
	file_controlplane_nodes_nodes_proto_depIdxs = nil
}
