// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: logs/logs.proto

package logs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_logs_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_logs_logs_proto_rawDescGZIP(), []int{0}
}

type LogFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	LastModified  string                 `protobuf:"bytes,3,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogFile) Reset() {
	*x = LogFile{}
	mi := &file_logs_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogFile) ProtoMessage() {}

func (x *LogFile) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogFile.ProtoReflect.Descriptor instead.
func (*LogFile) Descriptor() ([]byte, []int) {
	return file_logs_logs_proto_rawDescGZIP(), []int{1}
}

func (x *LogFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *LogFile) GetLastModified() string {
	if x != nil {
		return x.LastModified
	}
	return ""
}

type GetSystemLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*LogFile             `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemLogsResponse) Reset() {
	*x = GetSystemLogsResponse{}
	mi := &file_logs_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemLogsResponse) ProtoMessage() {}

func (x *GetSystemLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemLogsResponse.ProtoReflect.Descriptor instead.
func (*GetSystemLogsResponse) Descriptor() ([]byte, []int) {
	return file_logs_logs_proto_rawDescGZIP(), []int{2}
}

func (x *GetSystemLogsResponse) GetFiles() []*LogFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type ReadSystemLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSystemLogRequest) Reset() {
	*x = ReadSystemLogRequest{}
	mi := &file_logs_logs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSystemLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSystemLogRequest) ProtoMessage() {}

func (x *ReadSystemLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSystemLogRequest.ProtoReflect.Descriptor instead.
func (*ReadSystemLogRequest) Descriptor() ([]byte, []int) {
	return file_logs_logs_proto_rawDescGZIP(), []int{3}
}

func (x *ReadSystemLogRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReadSystemLogRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ReadSystemLogRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ReadSystemLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	TotalLines    int32                  `protobuf:"varint,2,opt,name=total_lines,json=totalLines,proto3" json:"total_lines,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSystemLogResponse) Reset() {
	*x = ReadSystemLogResponse{}
	mi := &file_logs_logs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSystemLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSystemLogResponse) ProtoMessage() {}

func (x *ReadSystemLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSystemLogResponse.ProtoReflect.Descriptor instead.
func (*ReadSystemLogResponse) Descriptor() ([]byte, []int) {
	return file_logs_logs_proto_rawDescGZIP(), []int{4}
}

func (x *ReadSystemLogResponse) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *ReadSystemLogResponse) GetTotalLines() int32 {
	if x != nil {
		return x.TotalLines
	}
	return 0
}

func (x *ReadSystemLogResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ReadSystemLogResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetServerLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerLogsRequest) Reset() {
	*x = GetServerLogsRequest{}
	mi := &file_logs_logs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerLogsRequest) ProtoMessage() {}

func (x *GetServerLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerLogsRequest.ProtoReflect.Descriptor instead.
func (*GetServerLogsRequest) Descriptor() ([]byte, []int) {
	return file_logs_logs_proto_rawDescGZIP(), []int{5}
}

func (x *GetServerLogsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type GetServerLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*LogFile             `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerLogsResponse) Reset() {
	*x = GetServerLogsResponse{}
	mi := &file_logs_logs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerLogsResponse) ProtoMessage() {}

func (x *GetServerLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerLogsResponse.ProtoReflect.Descriptor instead.
func (*GetServerLogsResponse) Descriptor() ([]byte, []int) {
	return file_logs_logs_proto_rawDescGZIP(), []int{6}
}

func (x *GetServerLogsResponse) GetFiles() []*LogFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type ReadServerLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadServerLogRequest) Reset() {
	*x = ReadServerLogRequest{}
	mi := &file_logs_logs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadServerLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadServerLogRequest) ProtoMessage() {}

func (x *ReadServerLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadServerLogRequest.ProtoReflect.Descriptor instead.
func (*ReadServerLogRequest) Descriptor() ([]byte, []int) {
	return file_logs_logs_proto_rawDescGZIP(), []int{7}
}

func (x *ReadServerLogRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ReadServerLogRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReadServerLogRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ReadServerLogRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ReadServerLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	TotalLines    int32                  `protobuf:"varint,2,opt,name=total_lines,json=totalLines,proto3" json:"total_lines,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadServerLogResponse) Reset() {
	*x = ReadServerLogResponse{}
	mi := &file_logs_logs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadServerLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadServerLogResponse) ProtoMessage() {}

func (x *ReadServerLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadServerLogResponse.ProtoReflect.Descriptor instead.
func (*ReadServerLogResponse) Descriptor() ([]byte, []int) {
	return file_logs_logs_proto_rawDescGZIP(), []int{8}
}

func (x *ReadServerLogResponse) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *ReadServerLogResponse) GetTotalLines() int32 {
	if x != nil {
		return x.TotalLines
	}
	return 0
}

func (x *ReadServerLogResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ReadServerLogResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_logs_logs_proto protoreflect.FileDescriptor

const file_logs_logs_proto_rawDesc = "" +
	"\n" +
	"\x0flogs/logs.proto\x12\x04logs\"\a\n" +
	"\x05Empty\"V\n" +
	"\aLogFile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12#\n" +
	"\rlast_modified\x18\x03 \x01(\tR\flastModified\"<\n" +
	"\x15GetSystemLogsResponse\x12#\n" +
	"\x05files\x18\x01 \x03(\v2\r.logs.LogFileR\x05files\"c\n" +
	"\x14ReadSystemLogRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x92\x01\n" +
	"\x15ReadSystemLogResponse\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines\x12\x1f\n" +
	"\vtotal_lines\x18\x02 \x01(\x05R\n" +
	"totalLines\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"3\n" +
	"\x14GetServerLogsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"<\n" +
	"\x15GetServerLogsResponse\x12#\n" +
	"\x05files\x18\x01 \x03(\v2\r.logs.LogFileR\x05files\"\x80\x01\n" +
	"\x14ReadServerLogRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x92\x01\n" +
	"\x15ReadServerLogResponse\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines\x12\x1f\n" +
	"\vtotal_lines\x18\x02 \x01(\x05R\n" +
	"totalLines\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages2\xa6\x02\n" +
	"\vLogsService\x129\n" +
	"\rGetSystemLogs\x12\v.logs.Empty\x1a\x1b.logs.GetSystemLogsResponse\x12H\n" +
	"\rReadSystemLog\x12\x1a.logs.ReadSystemLogRequest\x1a\x1b.logs.ReadSystemLogResponse\x12H\n" +
	"\rGetServerLogs\x12\x1a.logs.GetServerLogsRequest\x1a\x1b.logs.GetServerLogsResponse\x12H\n" +
	"\rReadServerLog\x12\x1a.logs.ReadServerLogRequest\x1a\x1b.logs.ReadServerLogResponseB3Z1github.com/zhinea/sylix/internal/infra/proto/logsb\x06proto3"

var (
	file_logs_logs_proto_rawDescOnce sync.Once
	file_logs_logs_proto_rawDescData []byte
)

func file_logs_logs_proto_rawDescGZIP() []byte {
	file_logs_logs_proto_rawDescOnce.Do(func() {
		file_logs_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logs_logs_proto_rawDesc), len(file_logs_logs_proto_rawDesc)))
	})
	return file_logs_logs_proto_rawDescData
}

var file_logs_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_logs_logs_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: logs.Empty
	(*LogFile)(nil),               // 1: logs.LogFile
	(*GetSystemLogsResponse)(nil), // 2: logs.GetSystemLogsResponse
	(*ReadSystemLogRequest)(nil),  // 3: logs.ReadSystemLogRequest
	(*ReadSystemLogResponse)(nil), // 4: logs.ReadSystemLogResponse
	(*GetServerLogsRequest)(nil),  // 5: logs.GetServerLogsRequest
	(*GetServerLogsResponse)(nil), // 6: logs.GetServerLogsResponse
	(*ReadServerLogRequest)(nil),  // 7: logs.ReadServerLogRequest
	(*ReadServerLogResponse)(nil), // 8: logs.ReadServerLogResponse
}
var file_logs_logs_proto_depIdxs = []int32{
	1, // 0: logs.GetSystemLogsResponse.files:type_name -> logs.LogFile
	1, // 1: logs.GetServerLogsResponse.files:type_name -> logs.LogFile
	0, // 2: logs.LogsService.GetSystemLogs:input_type -> logs.Empty
	3, // 3: logs.LogsService.ReadSystemLog:input_type -> logs.ReadSystemLogRequest
	5, // 4: logs.LogsService.GetServerLogs:input_type -> logs.GetServerLogsRequest
	7, // 5: logs.LogsService.ReadServerLog:input_type -> logs.ReadServerLogRequest
	2, // 6: logs.LogsService.GetSystemLogs:output_type -> logs.GetSystemLogsResponse
	4, // 7: logs.LogsService.ReadSystemLog:output_type -> logs.ReadSystemLogResponse
	6, // 8: logs.LogsService.GetServerLogs:output_type -> logs.GetServerLogsResponse
	8, // 9: logs.LogsService.ReadServerLog:output_type -> logs.ReadServerLogResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_logs_logs_proto_init() }
func file_logs_logs_proto_init() {
	if File_logs_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logs_logs_proto_rawDesc), len(file_logs_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logs_logs_proto_goTypes,
		DependencyIndexes: file_logs_logs_proto_depIdxs,
		MessageInfos:      file_logs_logs_proto_msgTypes,
	}.Build()
	File_logs_logs_proto = out.File
	file_logs_logs_proto_goTypes = nil
	file_logs_logs_proto_depIdxs = nil
}
